export const officeProductivityCourses = [
  {
    id: 1,
    title: "Mastering Microsoft Excel: From Beginner to Pro",
    instructor: "John Doe",
    rating: 4.7,
    reviewCount: 15243,
    price: 2074.17,
    originalPrice: 2499.17,
    currency: "INR",
    description:
      "Unlock the full potential of Microsoft Excel. Learn advanced formulas, pivot tables, and data visualization techniques to streamline your workflow and analyze data like a pro.",
    imageUrl: "/assets/officeProductivity/ms-excel.png",
    status: "new",
    badge: "Bestseller",
    level: "Beginner to Advanced",
    language: "English",
    duration: "12h 30m",
    lectures: 85,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Learn essential Excel formulas and functions",
      "Master Pivot Tables and Pivot Charts",
      "Build interactive dashboards",
      "Data analysis & visualization techniques",
      "Automation using Macros & VBA basics",
    ],
    requirements: [
      "No prior Excel experience needed",
      "A computer with Excel installed",
      "Willingness to practice with real datasets",
    ],
    whatYouWillLearn: [
      "Create professional reports using Excel",
      "Analyze large datasets with ease",
      "Design interactive dashboards",
      "Automate repetitive tasks using Macros",
    ],
    targetAudience: [
      "Students who want to boost productivity",
      "Business analysts & data professionals",
      "Anyone looking to upgrade Excel skills",
      "Job seekers who want an edge in interviews",
    ],
    subPage: "Microsoft-Office",
    reviews: [
      {
        id: 1,
        user: "Alex T.",
        date: "July 20, 2025",
        comment:
          "The section on Pivot Tables was a game-changer for me. The instructor explains everything so clearly!",
      },
      {
        id: 2,
        user: "Priya S.",
        date: "July 15, 2025",
        comment:
          "I've been using Excel for years, but this course taught me so many new formulas and shortcuts. Highly recommend!",
      },
      {
        id: 3,
        user: "Rajesh K.",
        date: "July 10, 2025",
        comment:
          "The project-based learning approach is fantastic. I now feel confident using Excel for my job. Great value for the price!",
      },
    ],
  },
  {
    id: 2,
    title: "Google Workspace: The Complete Productivity Toolkit",
    instructor: "Jane Smith",
    rating: 4.8,
    reviewCount: 11890,
    price: 1659.17,
    originalPrice: 1999.17,
    currency: "INR",
    description:
      "Boost your productivity with Google Docs, Sheets, and Slides. This course covers collaboration features, shortcuts, and advanced settings to help you work efficiently in the cloud.",
    imageUrl: "/assets/officeProductivity/Google-Workspace.png",
    status: "popular",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "8h 15m",
    lectures: 60,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Master Google Docs, Sheets, and Slides",
      "Learn advanced collaboration features",
      "Utilize shortcuts to save time",
      "Work efficiently in a cloud environment",
      "Integrate with other Google services",
    ],
    requirements: [
      "A Google account",
      "Basic computer literacy",
      "Internet connection",
    ],
    whatYouWillLearn: [
      "Create professional documents and presentations",
      "Analyze data with Google Sheets functions",
      "Collaborate in real-time with your team",
      "Automate tasks with Google App Script basics",
    ],
    targetAudience: [
      "Students & professionals using Google Workspace",
      "Small business owners",
      "Remote teams and collaborators",
    ],
    subPage: "Google-Workspace",
    reviews: [
      {
        id: 1,
        user: "Maria G.",
        date: "June 25, 2025",
        comment:
          "This course made me a Google Sheets wizard! I've saved so much time with the automation tips.",
      },
      {
        id: 2,
        user: "Ben L.",
        date: "June 18, 2025",
        comment:
          "Fantastic for anyone who works with remote teams. The collaboration features covered are a must-know.",
      },
      {
        id: 3,
        user: "Sonia P.",
        date: "June 12, 2025",
        comment:
          "Clear, concise, and straight to the point. Learned all the key features of Google Workspace quickly.",
      },
    ],
  },
  {
    id: 3,
    title:
      "Time Management Mastery: Conquer Procrastination and Get Things Done",
    instructor: "Robert Johnson",
    rating: 4.6,
    reviewCount: 9750,
    price: 2489.17,
    originalPrice: 2999.17,
    currency: "INR",
    description:
      "Learn proven strategies to manage your time effectively, set priorities, and eliminate distractions. Develop a personalized system to achieve your goals and reduce stress.",
    imageUrl: "/assets/officeProductivity/Time-Management-Mastery.png",
    status: "trending",
    badge: "Premium",
    level: "All Levels",
    language: "English",
    duration: "5h 45m",
    lectures: 40,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "German"],
    highlights: [
      "Identify and overcome procrastination",
      "Learn goal-setting frameworks",
      "Implement time-blocking techniques",
      "Minimize distractions and stay focused",
      "Create a sustainable personal productivity system",
    ],
    requirements: [
      "A notebook and pen",
      "Willingness to experiment with new habits",
    ],
    whatYouWillLearn: [
      "Take control of your daily schedule",
      "Achieve more in less time",
      "Reduce stress and improve work-life balance",
      "Develop habits for long-term productivity",
    ],
    targetAudience: [
      "Anyone struggling with procrastination",
      "Busy professionals and students",
      "Entrepreneurs and freelancers",
      "Individuals seeking better work-life balance",
    ],
    subPage: "Time-Management",
    reviews: [
      {
        id: 1,
        user: "Kevin C.",
        date: "July 18, 2025",
        comment:
          "This course helped me finally beat my procrastination habit. The techniques are simple to implement and really work.",
      },
      {
        id: 2,
        user: "Fatima R.",
        date: "July 14, 2025",
        comment:
          "I feel so much more in control of my time. The section on time-blocking was a game-changer for my workflow.",
      },
      {
        id: 3,
        user: "Sam H.",
        date: "July 9, 2025",
        comment:
          "Excellent course for anyone who feels overwhelmed. The content is practical and easy to apply immediately.",
      },
    ],
  },
  {
    id: 4,
    title: "The Art of Professional Communication",
    instructor: "Emily White",
    rating: 4.9,
    reviewCount: 18502,
    price: 2904.17,
    originalPrice: 3499.17,
    currency: "INR",
    description:
      "Improve your written and verbal communication skills for the workplace. This course covers email etiquette, presentation skills, and active listening to help you communicate clearly and confidently.",
    imageUrl: "/assets/officeProductivity/Professional-Communication.png",
    status: "new",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "7h 00m",
    lectures: 55,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Master effective email etiquette",
      "Develop persuasive presentation skills",
      "Practice active listening techniques",
      "Learn to handle difficult conversations",
      "Build rapport and professional relationships",
    ],
    requirements: [
      "Basic understanding of professional settings",
      "Willingness to practice and apply feedback",
    ],
    whatYouWillLearn: [
      "Communicate clearly and concisely",
      "Deliver impactful presentations",
      "Write professional and effective emails",
      "Improve your verbal and non-verbal cues",
    ],
    targetAudience: [
      "New graduates entering the workforce",
      "Professionals seeking career advancement",
      "Team leaders and managers",
      "Anyone who wants to improve their interpersonal skills",
    ],
    subPage: "Communication",
    reviews: [
      {
        id: 1,
        user: "Sarah M.",
        date: "August 22, 2025",
        comment:
          "I'm so much more confident in meetings now. The presentation tips were incredibly helpful!",
      },
      {
        id: 2,
        user: "David J.",
        date: "August 19, 2025",
        comment:
          "The email etiquette section alone was worth the price. I've completely changed how I write professional emails.",
      },
      {
        id: 3,
        user: "Chen W.",
        date: "August 15, 2025",
        comment:
          "Great course for improving soft skills. The instructor's advice on active listening is something I'll use forever.",
      },
    ],
  },
  {
    id: 5,
    title: "Project Management with Asana and Trello",
    instructor: "Chris Evans",
    rating: 4.5,
    reviewCount: 7890,
    price: 1908.17,
    originalPrice: 2299.17,
    currency: "INR",
    description:
      "Take control of your projects using leading productivity tools. Learn how to create task boards, manage timelines, and collaborate with your team to deliver projects on time.",
    imageUrl:
      "/assets/officeProductivity/Project-Management-with-Asana-and-Trello.png",
    status: "popular",
    badge: "Premium",
    level: "Beginner",
    language: "English",
    duration: "6h 30m",
    lectures: 45,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "French"],
    highlights: [
      "Set up and manage projects in Asana",
      "Create and utilize Trello boards",
      "Assign tasks and track progress",
      "Manage timelines and dependencies",
      "Collaborate effectively with your team",
    ],
    requirements: [
      "A computer with internet access",
      "A free Asana and/or Trello account",
    ],
    whatYouWillLearn: [
      "Organize personal and team projects",
      "Keep projects on track and on budget",
      "Improve team communication",
      "Use automation features to save time",
    ],
    targetAudience: [
      "Small business owners",
      "Team members and project coordinators",
      "Freelancers managing multiple clients",
      "Students working on group projects",
    ],
    subPage: "Project-Management",
    reviews: [
      {
        id: 1,
        user: "Leo B.",
        date: "July 28, 2025",
        comment:
          "I had no idea how to use Asana, but this course broke it down perfectly. My team projects are so much smoother now.",
      },
      {
        id: 2,
        user: "Hannah R.",
        date: "July 21, 2025",
        comment:
          "As a freelancer, this course was invaluable. I now have a clear system for managing all my client work.",
      },
      {
        id: 3,
        user: "Daniel F.",
        date: "July 16, 2025",
        comment:
          "The Trello section was great for setting up my personal tasks. Highly recommend for anyone who needs to get organized.",
      },
    ],
  },
  {
    id: 6,
    title: "Digital Note-Taking with Evernote and OneNote",
    instructor: "Sarah Lee",
    rating: 4.7,
    reviewCount: 6210,
    price: 1244.17,
    originalPrice: 1499.17,
    currency: "INR",
    description:
      "Organize your thoughts and information with powerful digital note-taking apps. Discover how to sync notes across devices, clip web pages, and create a searchable knowledge base.",
    imageUrl: "/assets/officeProductivity/Digital-Note-Taking.png",
    status: "trending",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "4h 00m",
    lectures: 35,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Set up an effective note-taking system",
      "Use tags and notebooks to stay organized",
      "Integrate with other apps and services",
      "Master search functionality to find anything",
      "Sync notes across all your devices",
    ],
    requirements: [
      "A computer or mobile device",
      "A free Evernote or OneNote account",
    ],
    whatYouWillLearn: [
      "Capture and organize all your ideas",
      "Create a digital filing system",
      "Save and annotate web pages",
      "Improve information recall",
    ],
    targetAudience: [
      "Students and researchers",
      "Writers and content creators",
      "Professionals who manage lots of information",
      "Anyone who wants to go paperless",
    ],
    subPage: "Microsoft-Office",
    reviews: [
      {
        id: 1,
        user: "Chloe P.",
        date: "July 29, 2025",
        comment:
          "I've tried digital note-taking before but couldn't get the hang of it. This course's system for organization is brilliant!",
      },
      {
        id: 2,
        user: "Mark D.",
        date: "July 25, 2025",
        comment:
          "The tips on using tags and search were exactly what I needed. I can now find old notes in seconds.",
      },
      {
        id: 3,
        user: "Lisa W.",
        date: "July 20, 2025",
        comment:
          "Great for students! I'm using these methods to organize all my research and class notes.",
      },
    ],
  },
  {
    id: 7,
    title: "Public Speaking for Professionals",
    instructor: "David Chen",
    rating: 4.8,
    reviewCount: 9876,
    price: 2323.17,
    originalPrice: 2799.17,
    currency: "INR",
    description:
      "Overcome your fear of public speaking and deliver engaging presentations. This course teaches you how to structure your speech, use visual aids, and captivate your audience.",
    imageUrl:
      "/assets/officeProductivity/Public-Speaking-for-Professionals.png",
    status: "new",
    badge: "Premium",
    level: "All Levels",
    language: "English",
    duration: "6h 15m",
    lectures: 50,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Hindi", "Mandarin"],
    highlights: [
      "Conquer stage fright and anxiety",
      "Structure a compelling narrative",
      "Use body language and vocal variety",
      "Design effective visual aids",
      "Engage and interact with your audience",
    ],
    requirements: [
      "Willingness to practice",
      "A computer with a microphone/camera",
    ],
    whatYouWillLearn: [
      "Deliver confident and impactful speeches",
      "Create presentations that resonate",
      "Manage Q&A sessions effectively",
      "Turn nerves into positive energy",
    ],
    targetAudience: [
      "Professionals who present in meetings",
      "Sales and marketing professionals",
      "Trainers and educators",
      "Students giving academic presentations",
    ],
    subPage: "Communication",
    reviews: [
      {
        id: 1,
        user: "Michael S.",
        date: "August 20, 2025",
        comment:
          "This course helped me conquer my fear of public speaking. The tips on body language and stage presence are incredibly effective.",
      },
      {
        id: 2,
        user: "Tina L.",
        date: "August 17, 2025",
        comment:
          "The section on structuring a narrative was a game-changer. My presentations are now so much more compelling.",
      },
      {
        id: 3,
        user: "James F.",
        date: "August 12, 2025",
        comment:
          "Practical, actionable advice that you can apply right away. I feel much more confident delivering my message.",
      },
    ],
  },
  {
    id: 8,
    title: "Advanced Excel Power Query & Power Pivot",
    instructor: "Michael Brown",
    rating: 4.6,
    reviewCount: 5120,
    price: 3320.17,
    originalPrice: 3999.17,
    currency: "INR",
    description:
      "Dive deep into data transformation and modeling with Excel's powerful tools. Automate data cleanup and build robust data models for powerful analysis.",
    imageUrl: "/assets/officeProductivity/Advanced-Excel.png",
    status: "popular",
    badge: "Premium",
    level: "Advanced",
    language: "English",
    duration: "10h 00m",
    lectures: 75,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Import and transform data with Power Query",
      "Create data models with Power Pivot",
      "Write advanced DAX formulas",
      "Automate data extraction and cleaning",
      "Build dynamic and complex reports",
    ],
    requirements: [
      "Intermediate Excel knowledge",
      "A computer with Excel 2016 or newer",
    ],
    whatYouWillLearn: [
      "Master data transformation and analysis",
      "Build powerful data models for business intelligence",
      "Automate repetitive reporting tasks",
      "Perform complex calculations with DAX",
    ],
    targetAudience: [
      "Data analysts and business intelligence professionals",
      "Accountants and finance professionals",
      "Anyone who works with large datasets in Excel",
    ],
    subPage: "Microsoft-Office",
    reviews: [
      {
        id: 1,
        user: "Prakash V.",
        date: "July 22, 2025",
        comment:
          "The DAX formula section was exactly what I was looking for. This course takes Excel to a professional level.",
      },
      {
        id: 2,
        user: "Emily F.",
        date: "July 18, 2025",
        comment:
          "Finally, a course that explains Power Query in a way that makes sense! My data cleaning process is now so much faster.",
      },
      {
        id: 3,
        user: "Ravi G.",
        date: "July 14, 2025",
        comment:
          "A fantastic deep dive into the advanced features of Excel. Essential for any data professional.",
      },
    ],
  },
  {
    id: 9,
    title: "Effective Email Management with Gmail",
    instructor: "Jessica Adams",
    rating: 4.7,
    reviewCount: 14500,
    price: 1490.17,
    originalPrice: 1799.17,
    currency: "INR",
    description:
      "Organize your inbox, automate tasks, and use advanced Gmail features to save time and stay on top of your communication.",
    imageUrl: "/assets/officeProductivity/Effective-Email-Management.png",
    status: "trending",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "3h 45m",
    lectures: 30,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Organize your inbox with labels and filters",
      "Automate email sorting and responses",
      "Utilize advanced search operators",
      "Master Gmail's keyboard shortcuts",
      "Understand email etiquette for professionals",
    ],
    requirements: ["A free or paid Google Workspace account"],
    whatYouWillLearn: [
      "Achieve Inbox Zero and stay organized",
      "Save time by automating repetitive tasks",
      "Find any email instantly",
      "Communicate more efficiently and professionally",
    ],
    targetAudience: [
      "Anyone who feels overwhelmed by email",
      "Professionals who use Gmail daily",
      "Students managing university correspondence",
    ],
    subPage: "Google-Workspace",
    reviews: [
      {
        id: 1,
        user: "Chris L.",
        date: "June 29, 2025",
        comment:
          "Inbox Zero is no longer a dream! The tips on using filters and labels are a lifesaver.",
      },
      {
        id: 2,
        user: "Sarah H.",
        date: "June 23, 2025",
        comment:
          "This course is short but packed with so much useful information. I've completely changed my email habits.",
      },
      {
        id: 3,
        user: "Arjun N.",
        date: "June 19, 2025",
        comment:
          "Finally learned how to use Gmail shortcuts properly. My productivity has increased dramatically.",
      },
    ],
  },
  {
    id: 10,
    title: "The Eisenhower Matrix: Prioritization for Productivity",
    instructor: "Daniel Harris",
    rating: 4.5,
    reviewCount: 8100,
    price: 1850.17,
    originalPrice: 2199.17,
    currency: "INR",
    description:
      "Master the art of prioritization using the famous Eisenhower Matrix. Learn to differentiate between urgent and important tasks to focus on what truly matters.",
    imageUrl: "/assets/officeProductivity/The-Eisenhower-Matrix.png",
    status: "new",
    badge: "Premium",
    level: "Beginner",
    language: "English",
    duration: "2h 30m",
    lectures: 20,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Learn the core principles of the Eisenhower Matrix",
      "Differentiate between urgent and important tasks",
      "Develop a habit of effective prioritization",
      "Eliminate time-wasting activities",
    ],
    requirements: [
      "No prior experience needed",
      "A desire to improve time management",
    ],
    whatYouWillLearn: [
      "Identify and focus on high-impact tasks",
      "Reduce stress and feel more in control",
      "Make better decisions about how to spend your time",
      "Stop putting out fires and start planning ahead",
    ],
    targetAudience: [
      "Individuals feeling overwhelmed by their to-do list",
      "Managers and team leaders",
      "Students balancing multiple assignments",
      "Anyone seeking a simple and powerful productivity tool",
    ],
    subPage: "Time-Management",
    reviews: [
      {
        id: 1,
        user: "Anna R.",
        date: "July 24, 2025",
        comment:
          "Such a simple but powerful framework. I'm now so much more intentional with how I spend my work day.",
      },
      {
        id: 2,
        user: "Ben C.",
        date: "July 19, 2025",
        comment:
          "The course is short and to the point, which is great for a productivity topic. The examples were very clear.",
      },
      {
        id: 3,
        user: "Lina M.",
        date: "July 16, 2025",
        comment:
          "I finally understand the difference between urgent and important tasks. My stress levels have gone down significantly.",
      },
    ],
  },
  {
    id: 11,
    title: "Agile Project Management Fundamentals",
    instructor: "Laura Parker",
    rating: 4.8,
    reviewCount: 10350,
    price: 3150.17,
    originalPrice: 3799.17,
    currency: "INR",
    description:
      "Learn the core principles of Agile and Scrum to manage projects effectively. Understand sprint planning, daily stand-ups, and retrospectives.",
    imageUrl: "https://placehold.co/400x250/333333/FFFFFF?text=Agile+PM",
    status: "popular",
    badge: "Bestseller",
    level: "Beginner",
    language: "English",
    duration: "8h 00m",
    lectures: 65,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "French"],
    highlights: [
      "Understand the Agile Manifesto and its principles",
      "Learn the Scrum framework and its ceremonies",
      "Master user story writing and backlog management",
      "Participate in sprint planning and reviews",
      "Collaborate effectively in an Agile team",
    ],
    requirements: [
      "No prior project management experience needed",
      "An open mind to a new way of working",
    ],
    whatYouWillLearn: [
      "Manage projects with a flexible and iterative approach",
      "Improve team communication and efficiency",
      "Respond quickly to changing project requirements",
      "Deliver value to stakeholders more frequently",
    ],
    targetAudience: [
      "New project managers and coordinators",
      "Software developers and IT professionals",
      "Business professionals moving to an Agile environment",
      "Anyone interested in modern project management",
    ],
    subPage: "Project-Management",
    reviews: [
      {
        id: 1,
        user: "Sophie G.",
        date: "August 20, 2025",
        comment:
          "As a new project coordinator, this was the perfect introduction to Agile. The lessons on Scrum ceremonies were very clear.",
      },
      {
        id: 2,
        user: "Daniel B.",
        date: "August 15, 2025",
        comment:
          "The course provides a great foundation for anyone looking to work in an Agile environment. It's concise and easy to follow.",
      },
      {
        id: 3,
        user: "Elena F.",
        date: "August 10, 2025",
        comment:
          "The instructor does a great job of explaining complex Agile concepts with simple, real-world examples.",
      },
    ],
  },
  {
    id: 12,
    title: "Business Writing & Grammar Refresher",
    instructor: "Kevin Miller",
    rating: 4.7,
    reviewCount: 7800,
    price: 2070.17,
    originalPrice: 2499.17,
    currency: "INR",
    description:
      "Polish your professional writing with this comprehensive course. Learn to write clear, concise, and impactful reports, emails, and presentations.",
    imageUrl:
      "https://placehold.co/400x250/b74384/FFFFFF?text=Business+Writing",
    status: "trending",
    badge: "Premium",
    level: "All Levels",
    language: "English",
    duration: "6h 45m",
    lectures: 50,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Review essential grammar and punctuation rules",
      "Learn to write with a professional tone",
      "Structure clear and concise emails and reports",
      "Avoid common writing mistakes",
      "Craft persuasive and impactful business documents",
    ],
    requirements: [
      "Basic English proficiency",
      "Willingness to practice writing exercises",
    ],
    whatYouWillLearn: [
      "Communicate more effectively through writing",
      "Write clear, error-free professional documents",
      "Improve your credibility and authority at work",
      "Save time by writing more efficiently",
    ],
    targetAudience: [
      "Professionals who write emails and reports daily",
      "Job seekers preparing for professional correspondence",
      "Students working on academic papers",
      "Anyone wanting to sharpen their business writing skills",
    ],
    subPage: "Communication",
    reviews: [
      {
        id: 1,
        user: "Omar K.",
        date: "July 29, 2025",
        comment:
          "This course is a must-have for anyone who writes professional emails. It's a fantastic refresher and taught me so many new things.",
      },
      {
        id: 2,
        user: "Jessica W.",
        date: "July 24, 2025",
        comment:
          "I finally feel confident in my writing at work. The tips on professional tone and structure were the most helpful.",
      },
      {
        id: 3,
        user: "Ken S.",
        date: "July 20, 2025",
        comment:
          "The exercises were great for putting the concepts into practice. Highly recommend to anyone who wants to improve their business writing.",
      },
    ],
  },
  {
    id: 13,
    title: "Microsoft PowerPoint: The Ultimate Presentation Guide",
    instructor: "Olivia King",
    rating: 4.6,
    reviewCount: 9250,
    price: 1890.17,
    originalPrice: 2299.17,
    currency: "INR",
    description:
      "Create stunning, professional presentations with Microsoft PowerPoint. Learn to design engaging slides, use animations, and master presentation delivery.",
    imageUrl: "https://placehold.co/400x250/50b86a/FFFFFF?text=PowerPoint",
    status: "new",
    badge: "Bestseller",
    level: "Beginner to Advanced",
    language: "English",
    duration: "7h 30m",
    lectures: 60,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Design visually appealing slides",
      "Master animation and transition effects",
      "Create charts, graphs, and smart art",
      "Learn presentation delivery techniques",
      "Utilize speaker notes and rehearse your presentation",
    ],
    requirements: [
      "A computer with Microsoft PowerPoint installed",
      "Basic computer literacy",
    ],
    whatYouWillLearn: [
      "Create presentations that impress your audience",
      "Communicate complex ideas simply",
      "Deliver your message with confidence and clarity",
      "Save time with design templates and shortcuts",
    ],
    targetAudience: [
      "Students and academic professionals",
      "Business professionals and marketers",
      "Anyone who needs to create and deliver presentations",
    ],
    subPage: "Microsoft-Office",
    reviews: [
      {
        id: 1,
        user: "Grace K.",
        date: "July 29, 2025",
        comment:
          "The design principles taught in this course have completely elevated my presentations. The slides look so much more professional now.",
      },
      {
        id: 2,
        user: "Leo R.",
        date: "July 25, 2025",
        comment:
          "I used to be a mess with animations, but this course made it so easy. My presentations are now dynamic and engaging.",
      },
      {
        id: 3,
        user: "Sarah L.",
        date: "July 21, 2025",
        comment:
          "A great course for both beginners and those who want to polish their skills. The delivery techniques were a huge bonus.",
      },
    ],
  },
  {
    id: 14,
    title: "Google Sheets for Data Analysis",
    instructor: "Ryan Green",
    rating: 4.7,
    reviewCount: 8720,
    price: 2580.17,
    originalPrice: 3099.17,
    currency: "INR",
    description:
      "Leverage Google Sheets for powerful data analysis. Master functions, pivot tables, and advanced charting to make data-driven decisions.",
    imageUrl: "https://placehold.co/400x250/20658f/FFFFFF?text=Google+Sheets",
    status: "popular",
    badge: "Premium",
    level: "Beginner to Intermediate",
    language: "English",
    duration: "9h 15m",
    lectures: 70,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Master essential and advanced Google Sheets formulas",
      "Create and customize pivot tables",
      "Build dynamic charts and dashboards",
      "Automate tasks with Google App Script",
      "Collaborate on data projects in real-time",
    ],
    requirements: ["A Google account", "A computer with internet connection"],
    whatYouWillLearn: [
      "Clean and prepare data for analysis",
      "Extract insights from raw data",
      "Create visual representations of data",
      "Make better business decisions with data",
    ],
    targetAudience: [
      "Analysts and data scientists",
      "Small business owners and managers",
      "Students working on data projects",
      "Anyone interested in data-driven decision making",
    ],
    subPage: "Google-Workspace",
    reviews: [
      {
        id: 1,
        user: "Kevin B.",
        date: "August 22, 2025",
        comment:
          "This course transformed my workflow. The lessons on pivot tables and advanced functions are excellent.",
      },
      {
        id: 2,
        user: "Maya P.",
        date: "August 19, 2025",
        comment:
          "A must-have for anyone who wants to go beyond basic spreadsheets. The data analysis tips were very insightful.",
      },
      {
        id: 3,
        user: "Tom W.",
        date: "August 15, 2025",
        comment:
          "The content on Google App Script for automation was a huge bonus. I've already automated several tasks.",
      },
    ],
  },
  {
    id: 15,
    title: "The Pomodoro Technique: Focus and Productivity",
    instructor: "Sophia Turner",
    rating: 4.9,
    reviewCount: 12100,
    price: 1500.17,
    originalPrice: 1799.17,
    currency: "INR",
    description:
      "Learn a simple yet highly effective time management method to improve focus and productivity. Break down your work into manageable intervals with short breaks.",
    imageUrl:
      "https://placehold.co/400x250/f07010/FFFFFF?text=Pomodoro+Technique",
    status: "trending",
    badge: "Bestseller",
    level: "Beginner",
    language: "English",
    duration: "2h 00m",
    lectures: 15,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English", "Portuguese"],
    highlights: [
      "Understand the science behind the Pomodoro Technique",
      "Learn to set up your own Pomodoro sessions",
      "Minimize interruptions and distractions",
      "Use breaks to recharge and improve focus",
      "Combine Pomodoro with other productivity tools",
    ],
    requirements: [
      "A timer (physical or digital)",
      "A notebook or app to track tasks",
      "A desire to improve your focus",
    ],
    whatYouWillLearn: [
      "Maintain focus for extended periods",
      "Complete tasks more efficiently",
      "Overcome mental fatigue and burnout",
      "Feel a sense of accomplishment at the end of the day",
    ],
    targetAudience: [
      "Students studying for exams",
      "Remote workers and freelancers",
      "Professionals with demanding workloads",
      "Anyone who wants to combat procrastination",
    ],
    subPage: "Time-Management",
    reviews: [
      {
        id: 1,
        user: "John L.",
        date: "June 30, 2025",
        comment:
          "This is the most effective productivity method I've ever learned. The course is short but has a huge impact.",
      },
      {
        id: 2,
        user: "Lisa P.",
        date: "June 25, 2025",
        comment:
          "I've been using this for studying, and it has completely changed my focus. No more procrastination!",
      },
      {
        id: 3,
        user: "Sam A.",
        date: "June 21, 2025",
        comment:
          "A fantastic and simple course. The idea of taking short breaks has made me so much more productive.",
      },
    ],
  },
];

export const officeProductivityInstructors = [
  {
    name: "Leila Gharani",
    expertise: "Microsoft Excel, Data Analysis",
    rating: 4.8,
    students: "1,250,000",
    courses: 18,
    thumbnail: "https://placehold.co/100x100/2563eb/fff?text=LG",
  },
  {
    name: "Chris Croft",
    expertise: "Project Management, Time Management",
    rating: 4.7,
    students: "500,000",
    courses: 35,
    thumbnail: "https://placehold.co/100x100/16a34a/fff?text=CC",
  },
  {
    name: "Deb Ashby",
    expertise: "Microsoft Office, Productivity Tools",
    rating: 4.6,
    students: "300,000",
    courses: 22,
    thumbnail: "https://placehold.co/100x100/f97316/fff?text=DA",
  },
  {
    name: "David Rivers",
    expertise: "Google Workspace, Collaboration",
    rating: 4.5,
    students: "420,000",
    courses: 40,
    thumbnail: "https://placehold.co/100x100/9333ea/fff?text=DR",
  },
  {
    name: "Diane Hohman",
    expertise: "Email Productivity, Microsoft Outlook",
    rating: 4.6,
    students: "150,000",
    courses: 12,
    thumbnail: "https://placehold.co/100x100/f43f5e/fff?text=DH",
  },
];

export const officeProductivityTopics = [
  "Microsoft Excel",
  "Google Sheets",
  "Microsoft Word",
  "PowerPoint Design",
  "Google Workspace",
  "Outlook Productivity",
  "Project Management Tools",
  "Time Management",
  "Keyboard Shortcuts",
  "Data Visualization",
  "Note-taking with OneNote",
  "Task Management (Todoist, Trello, Asana)",
  "Email Management",
  "Remote Collaboration",
  "Automation with Zapier",
];
