export const personalDevelopmentCourses = [
  {
    id: 1,
    title: "Become a SuperLearner® 2: Learn Speed Reading & Boost Memory",
    instructor: "Akarsh Tyagi, Lev Goldentouch, Anna Goldentouch",
    rating: 4.3,
    reviewCount: 40520,
    price: 659.0,
    originalPrice: 4559.0,
    currency: "INR",
    description:
      "Learn to read faster, improve your memory, and acquire knowledge more efficiently. This course provides a comprehensive system for accelerated learning and cognitive improvement.",
    imageUrl: "/assets/PersonalDevelopmentPage/superlearner.png",
    status: "popular",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "4h 30m",
    lectures: 78,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Improve reading speed by 3x or more",
      "Boost memory retention and recall",
      "Develop powerful focus and concentration",
      "Learn to absorb information from any source",
      "Master proven memory techniques (mnemonics, etc.)",
    ],
    requirements: [
      "A notebook and pen",
      "Willingness to practice the techniques",
    ],
    whatYouWillLearn: [
      "Read books and articles at a much faster rate",
      "Remember names, numbers, and facts with ease",
      "Process information more efficiently for exams or work",
      "Train your brain to think and learn faster",
    ],
    targetAudience: [
      "Students preparing for exams",
      "Professionals who need to absorb large amounts of information",
      "Anyone wanting to improve their learning skills",
      "Individuals with memory or focus challenges",
    ],
    subPage: "learning-skills",
    reviews: [
      {
        id: 1,
        user: "Rohan S.",
        date: "July 20, 2025",
        comment:
          "This course is a game-changer. I'm now able to read complex documents in half the time.",
      },
      {
        id: 2,
        user: "Leena K.",
        date: "July 15, 2025",
        comment:
          "The memory techniques are incredible. I can now remember names and facts so much better.",
      },
      {
        id: 3,
        user: "Amit G.",
        date: "July 10, 2025",
        comment:
          "The practical exercises are great. I started seeing results after just a few lessons.",
      },
    ],
  },
  {
    id: 2,
    title: "Certified Life Coach Training (Beginner to Advanced)",
    instructor: "Kartikay Kandpal, The Academy of Applied Psychology",
    rating: 4.6,
    reviewCount: 38285,
    price: 659.0,
    originalPrice: 4389.0,
    currency: "INR",
    description:
      "Become a certified life coach and learn how to guide others to achieve their personal and professional goals. This course covers core coaching models, ethics, and business building.",
    imageUrl: "/assets/PersonalDevelopmentPage/lifecoach.png",
    status: "popular",
    badge: "Premium",
    level: "Beginner to Advanced",
    language: "English",
    duration: "10h 00m",
    lectures: 95,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Master core coaching competencies",
      "Learn goal-setting frameworks (SMART, GROW)",
      "Develop powerful communication and listening skills",
      "Understand the ethics of coaching",
      "Build a successful life coaching business",
    ],
    requirements: [
      "A passion for helping others",
      "Willingness to engage in role-playing exercises",
    ],
    whatYouWillLearn: [
      "Coach clients to overcome obstacles and achieve goals",
      "Create a professional coaching practice",
      "Build a strong rapport with clients",
      "Market your coaching services effectively",
    ],
    targetAudience: [
      "Aspiring and new life coaches",
      "Therapists, counselors, and mentors",
      "Managers and team leaders who want to coach their teams",
      "Individuals on a journey of personal growth",
    ],
    subPage: "coaching",
    reviews: [
      {
        id: 1,
        user: "Pooja D.",
        date: "June 25, 2025",
        comment:
          "This course gave me the confidence and tools to start my own coaching practice. The content is thorough and well-structured.",
      },
      {
        id: 2,
        user: "Vikram N.",
        date: "June 18, 2025",
        comment:
          "The instructor's real-world examples and practical advice were invaluable. Highly recommend!",
      },
      {
        id: 3,
        user: "Anjali S.",
        date: "June 12, 2025",
        comment:
          "I feel so much more prepared to help others now. The lessons on building a business were a huge bonus.",
      },
    ],
  },
  {
    id: 3,
    title: "NLP Practitioner Course (Neuro-Linguistic Programming)",
    instructor: "Avishkar, The Academy of Applied Psychology",
    rating: 4.6,
    reviewCount: 26388,
    price: 559.0,
    originalPrice: 3849.0,
    currency: "INR",
    description:
      "Explore the power of Neuro-Linguistic Programming to understand human behavior, improve communication, and create positive change in yourself and others.",
    imageUrl: "/assets/PersonalDevelopmentPage/nlp.png",
    status: "popular",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "8h 00m",
    lectures: 65,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Understand the principles of NLP",
      "Learn to reframe negative thought patterns",
      "Improve your communication and persuasion skills",
      "Set and achieve goals using NLP techniques",
      "Build rapport with anyone easily",
    ],
    requirements: [
      "An open mind and a desire for self-improvement",
      "Willingness to practice exercises and techniques",
    ],
    whatYouWillLearn: [
      "Change limiting beliefs and habits",
      "Enhance personal and professional relationships",
      "Communicate more effectively with others",
      "Influence and motivate yourself and others",
    ],
    targetAudience: [
      "Coaches, therapists, and trainers",
      "Sales and marketing professionals",
      "Anyone interested in psychology and self-improvement",
      "Leaders and managers seeking to motivate their teams",
    ],
    subPage: "communication",
    reviews: [
      {
        id: 1,
        user: "Sumit T.",
        date: "July 18, 2025",
        comment:
          "The content on reframing was incredibly helpful. I've already applied it to my own life with great results.",
      },
      {
        id: 2,
        user: "Kavya R.",
        date: "July 14, 2025",
        comment:
          "This course is a fantastic introduction to NLP. The instructor explains complex ideas in a simple, understandable way.",
      },
      {
        id: 3,
        user: "Rajesh P.",
        date: "July 9, 2025",
        comment:
          "I've learned so many practical techniques to improve my communication skills. A must-do course!",
      },
    ],
  },
  {
    id: 4,
    title: "The Complete Resume, LinkedIn & Get Your Dream Job Course!",
    instructor: "Chris Haroun",
    rating: 4.4,
    reviewCount: 7234,
    price: 529.0,
    originalPrice: 3659.0,
    currency: "INR",
    description:
      "Create a standout resume, optimize your LinkedIn profile, and master the job interview process to land your dream job in any industry.",
    imageUrl: "/assets/PersonalDevelopmentPage/linkedin_resume.png",
    status: "popular",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "6h 15m",
    lectures: 50,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Craft a professional and compelling resume",
      "Optimize your LinkedIn profile for recruiters",
      "Learn to network effectively",
      "Master common and difficult interview questions",
      "Negotiate your salary with confidence",
    ],
    requirements: [
      "A computer with internet access",
      "A current resume (or a blank document to start one)",
    ],
    whatYouWillLearn: [
      "Build a resume that gets past automated screeners",
      "Get noticed by recruiters on LinkedIn",
      "Ace your next job interview",
      "Gain the confidence to pursue your career goals",
    ],
    targetAudience: [
      "Job seekers at any career stage",
      "Students and recent graduates",
      "Anyone looking for a career change",
      "Professionals who want to improve their networking skills",
    ],
    subPage: "career-development",
    reviews: [
      {
        id: 1,
        user: "Alok J.",
        date: "July 20, 2025",
        comment:
          "I landed my dream job a month after taking this course! The salary negotiation tips were spot-on.",
      },
      {
        id: 2,
        user: "Divya R.",
        date: "July 15, 2025",
        comment:
          "The section on optimizing my LinkedIn profile was eye-opening. I'm now getting so many more views and messages from recruiters.",
      },
      {
        id: 3,
        user: "Rohit P.",
        date: "July 10, 2025",
        comment:
          "The resume templates provided were a huge help. This is a must-buy for anyone on the job hunt.",
      },
    ],
  },
  {
    id: 5,
    title: "Speak-up: Confident workplace presentations for beginners",
    instructor: "Mick Mason",
    rating: 4.9,
    reviewCount: 5,
    price: 449.0,
    originalPrice: 1679.0,
    currency: "INR",
    description:
      "Overcome your fear of public speaking and deliver confident, engaging presentations in a professional setting. This course is designed specifically for beginners.",
    imageUrl: "/assets/PersonalDevelopmentPage/speakwithconfidence.png",
    status: "new",
    badge: "New",
    level: "Beginner",
    language: "English",
    duration: "2h 00m",
    lectures: 25,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Manage public speaking anxiety",
      "Structure a clear and impactful presentation",
      "Use body language and voice to project confidence",
      "Engage your audience from start to finish",
      "Handle Q&A sessions effectively",
    ],
    requirements: [
      "A desire to improve your public speaking skills",
      "A computer with a microphone/camera for practice",
    ],
    whatYouWillLearn: [
      "Deliver presentations with confidence",
      "Communicate your ideas clearly in meetings",
      "Make a positive and lasting impression",
      "Transform your fear into powerful energy",
    ],
    targetAudience: [
      "Professionals who are new to public speaking",
      "Students preparing for class presentations",
      "Anyone who wants to feel more confident in meetings",
      "Individuals with social anxiety in professional settings",
    ],
    subPage: "communication",
    reviews: [
      {
        id: 1,
        user: "Arjun B.",
        date: "August 25, 2025",
        comment:
          "This course was exactly what I needed. The tips for managing anxiety before a presentation were so helpful.",
      },
      {
        id: 2,
        user: "Priyanka N.",
        date: "August 22, 2025",
        comment:
          "The instructor is great at making you feel comfortable and provides very actionable advice. I'm already seeing a difference.",
      },
      {
        id: 3,
        user: "Sanjay D.",
        date: "August 18, 2025",
        comment:
          "Short, to the point, and very effective. Perfect for a busy professional who needs a quick confidence boost.",
      },
    ],
  },
  {
    id: 6,
    title: "Business and Life Skills – All you need to succeed!",
    instructor: "Freedom Learning",
    rating: 5.0,
    reviewCount: 45,
    price: 449.0,
    originalPrice: 1679.0,
    currency: "INR",
    description:
      "A comprehensive course covering essential skills for both personal and professional success, including negotiation, leadership, and emotional intelligence.",
    imageUrl: "/assets/PersonalDevelopmentPage/businessandlifeskill.png",
    status: "new",
    badge: "New",
    level: "All Levels",
    language: "English",
    duration: "3h 30m",
    lectures: 40,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Develop strong leadership and management skills",
      "Master the art of negotiation",
      "Improve your emotional intelligence and self-awareness",
      "Learn effective problem-solving techniques",
      "Build a positive mindset for success",
    ],
    requirements: [
      "A desire to invest in your personal and professional growth",
    ],
    whatYouWillLearn: [
      "Navigate complex workplace challenges",
      "Build a rewarding and successful career",
      "Improve your interpersonal relationships",
      "Communicate with impact and confidence",
    ],
    targetAudience: [
      "Aspiring leaders and managers",
      "Entrepreneurs and business owners",
      "Recent graduates entering the workforce",
      "Anyone who wants to develop a well-rounded skill set",
    ],
    subPage: "soft-skills",
    reviews: [
      {
        id: 1,
        user: "Akash M.",
        date: "August 20, 2025",
        comment:
          "The course on negotiation was invaluable. I've already applied the techniques and saw a positive outcome.",
      },
      {
        id: 2,
        user: "Priya S.",
        date: "August 18, 2025",
        comment:
          "I love how this course covers both business and personal skills. It's a holistic approach to self-improvement.",
      },
      {
        id: 3,
        user: "Vivek G.",
        date: "August 15, 2025",
        comment:
          "The lessons are very practical and easy to apply. I feel more confident in my leadership role now.",
      },
    ],
  },
  {
    id: 7,
    title: "Naturopathy Fundamentals Course with Certification",
    instructor: "Ali Haider",
    rating: 5.0,
    reviewCount: 6,
    price: 449.0,
    originalPrice: 1679.0,
    currency: "INR",
    description:
      "Learn the core principles of naturopathy and holistic health. This course covers the natural methods for maintaining well-being, including nutrition, herbal remedies, and lifestyle changes.",
    imageUrl: "/assets/PersonalDevelopmentPage/naturopathyfundamentals.png",
    status: "new",
    badge: "New",
    level: "Beginner",
    language: "English",
    duration: "2h 45m",
    lectures: 30,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Understand the philosophy of naturopathic medicine",
      "Learn about the healing power of nutrition",
      "Explore the benefits of herbal remedies and supplements",
      "Discover the role of exercise and stress management",
      "Receive a certification upon completion",
    ],
    requirements: [
      "An interest in natural health and wellness",
      "A desire to learn about a holistic approach to health",
    ],
    whatYouWillLearn: [
      "Apply naturopathic principles to your daily life",
      "Improve your overall health and wellness naturally",
      "Understand the body's self-healing mechanisms",
      "Make informed decisions about your health",
    ],
    targetAudience: [
      "Individuals interested in natural health",
      "Health and wellness professionals",
      "Anyone who wants to live a more holistic lifestyle",
    ],
    subPage: "wellness",
    reviews: [
      {
        id: 1,
        user: "Meera P.",
        date: "August 20, 2025",
        comment:
          "A wonderful introduction to naturopathy. The instructor is knowledgeable and the content is easy to follow.",
      },
      {
        id: 2,
        user: "Tarun V.",
        date: "August 15, 2025",
        comment:
          "I've learned so much about the connection between diet and health. This course has motivated me to make healthier choices.",
      },
      {
        id: 3,
        user: "Ritu F.",
        date: "August 10, 2025",
        comment:
          "The certification is a great bonus. I highly recommend this to anyone curious about holistic health.",
      },
    ],
  },
  {
    id: 8,
    title: "Meditate on Self: Heal, Empower & Awaken Within",
    instructor: "Romi Ochwani",
    rating: 5.0,
    reviewCount: 6,
    price: 449.0,
    originalPrice: 1679.0,
    currency: "INR",
    description:
      "Learn to meditate for self-healing and personal growth. This course provides guided meditations and techniques to help you calm your mind, reduce stress, and connect with your inner self.",
    imageUrl: "/assets/PersonalDevelopmentPage/meditate.png",
    status: "new",
    badge: "New",
    level: "Beginner",
    language: "English",
    duration: "2h 00m",
    lectures: 20,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Understand the benefits of meditation",
      "Practice guided mindfulness and self-healing meditations",
      "Learn techniques to calm an anxious mind",
      "Develop a consistent meditation practice",
      "Connect with your intuition and inner wisdom",
    ],
    requirements: [
      "A quiet space to meditate",
      "No prior meditation experience needed",
    ],
    whatYouWillLearn: [
      "Reduce stress and anxiety",
      "Increase self-awareness and emotional regulation",
      "Improve focus and mental clarity",
      "Cultivate a sense of inner peace and well-being",
    ],
    targetAudience: [
      "Absolute beginners to meditation",
      "Individuals seeking stress relief and inner peace",
      "Anyone on a journey of spiritual or personal growth",
    ],
    subPage: "mindfulness",
    reviews: [
      {
        id: 1,
        user: "Geeta S.",
        date: "August 25, 2025",
        comment:
          "The guided meditations are beautiful and very effective. I feel so much calmer and more centered after each session.",
      },
      {
        id: 2,
        user: "Dev P.",
        date: "August 22, 2025",
        comment:
          "I've tried meditating before, but this course finally made it stick. The instructor's voice is very soothing.",
      },
      {
        id: 3,
        user: "Anushka R.",
        date: "August 18, 2025",
        comment:
          "A great course for anyone looking to heal and reconnect with themselves. I highly recommend it!",
      },
    ],
  },
  {
    id: 9,
    title: "ChatGPT: Complete ChatGPT Course For Work 2025 (Ethically)!",
    instructor: "Steve Ballinger, MBA",
    rating: 4.4,
    reviewCount: 114912,
    price: 659.0,
    originalPrice: 4129.0,
    currency: "INR",
    description:
      "Master ChatGPT and other AI tools to automate tasks, improve writing, and boost productivity in your professional life, all while learning to use them ethically and responsibly.",
    imageUrl: "/assets/PersonalDevelopmentPage/chatgpt.png",
    status: "trending",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "5h 15m",
    lectures: 55,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Write better emails, reports, and content with AI",
      "Automate tedious work tasks with ChatGPT",
      "Learn prompt engineering for optimal results",
      "Understand the ethical considerations of using AI",
      "Stay ahead of the curve with AI-powered skills",
    ],
    requirements: [
      "Access to ChatGPT or a similar AI tool",
      "A desire to improve work efficiency",
    ],
    whatYouWillLearn: [
      "Leverage AI to boost your productivity at work",
      "Create high-quality content and documents faster",
      "Use AI responsibly and ethically",
      "Become a power user of generative AI tools",
    ],
    targetAudience: [
      "Business professionals and entrepreneurs",
      "Writers and content creators",
      "Anyone interested in leveraging AI for productivity",
      "Managers and team leaders",
    ],
    subPage: "productivity",
    reviews: [
      {
        id: 1,
        user: "Samarth B.",
        date: "June 29, 2025",
        comment:
          "This course taught me so much more than just basic prompts. I'm now using ChatGPT to automate so many of my daily tasks.",
      },
      {
        id: 2,
        user: "Neha P.",
        date: "June 23, 2025",
        comment:
          "The ethical considerations section was a huge plus. It's great to see a course that focuses on responsible AI use.",
      },
      {
        id: 3,
        user: "Kunal S.",
        date: "June 19, 2025",
        comment:
          "I feel like I'm ahead of the game now. The course content is up-to-date and incredibly useful.",
      },
    ],
  },
  {
    id: 10,
    title: "Applying Mindfulness to Develop Resilience and Wellbeing",
    instructor: "Robin Hills",
    rating: 4.5,
    reviewCount: 5232,
    price: 449.0,
    originalPrice: 3199.0,
    currency: "INR",
    description:
      "Learn to build resilience and improve your overall well-being through the practice of mindfulness. This course provides practical tools to manage stress, navigate difficult emotions, and live with more presence.",
    imageUrl: "/assets/PersonalDevelopmentPage/mindfulness.png",
    status: "trending",
    badge: "Premium",
    level: "All Levels",
    language: "English",
    duration: "4h 00m",
    lectures: 35,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Understand the science of mindfulness and resilience",
      "Practice mindfulness exercises for daily life",
      "Develop emotional regulation skills",
      "Learn to navigate setbacks with strength",
      "Cultivate a greater sense of peace and calm",
    ],
    requirements: [
      "No prior experience with mindfulness needed",
      "A willingness to practice and be present",
    ],
    whatYouWillLearn: [
      "Reduce stress and anxiety in your life",
      "Bounce back from challenges and setbacks",
      "Live with more intention and presence",
      "Improve your mental and emotional health",
    ],
    targetAudience: [
      "Individuals experiencing stress or burnout",
      "Anyone wanting to improve their emotional resilience",
      "Professionals in high-stress environments",
      "People interested in personal and spiritual growth",
    ],
    subPage: "mindfulness",
    reviews: [
      {
        id: 1,
        user: "Simran K.",
        date: "July 25, 2025",
        comment:
          "The exercises are so simple but powerful. I've already noticed a huge difference in how I handle stressful situations.",
      },
      {
        id: 2,
        user: "Arun V.",
        date: "July 20, 2025",
        comment:
          "This course helped me realize the importance of being present. I feel much more grounded and less anxious.",
      },
      {
        id: 3,
        user: "Meera D.",
        date: "July 15, 2025",
        comment:
          "The instructor's approach is very empathetic and encouraging. A fantastic course for anyone's well-being journey.",
      },
    ],
  },
  {
    id: 11,
    title: "Time Management Mastery: Do More, Stress Less",
    instructor: "Alexis Haselberger",
    rating: 4.5,
    reviewCount: 82302,
    price: 469.0,
    originalPrice: 3779.0,
    currency: "INR",
    description:
      "Take control of your time and maximize productivity without feeling overwhelmed. This course teaches you proven strategies to prioritize tasks, set goals, and beat procrastination.",
    imageUrl: "/assets/PersonalDevelopmentPage/timemanagement.png",
    status: "trending",
    badge: "Premium",
    level: "All Levels",
    language: "English",
    duration: "5h 45m",
    lectures: 40,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Learn to prioritize tasks effectively",
      "Implement time-blocking and batching techniques",
      "Overcome the habit of procrastination",
      "Set realistic and achievable goals",
      "Create a personalized productivity system",
    ],
    requirements: ["A willingness to change your daily habits"],
    whatYouWillLearn: [
      "Increase your productivity and efficiency",
      "Reduce stress and burnout",
      "Take back control of your schedule",
      "Achieve your goals faster and with less effort",
    ],
    targetAudience: [
      "Students, freelancers, and entrepreneurs",
      "Professionals with demanding workloads",
      "Anyone who feels overwhelmed by their to-do list",
      "Individuals looking for better work-life balance",
    ],
    subPage: "productivity",
    reviews: [
      {
        id: 1,
        user: "Vishal K.",
        date: "July 28, 2025",
        comment:
          "The time-blocking method in this course is a game-changer. I'm now so much more intentional with my time.",
      },
      {
        id: 2,
        user: "Priya L.",
        date: "July 22, 2025",
        comment:
          "I finally feel like I can get everything done without working overtime. The tips on beating procrastination were especially helpful.",
      },
      {
        id: 3,
        user: "Ravi M.",
        date: "July 17, 2025",
        comment:
          "A practical and actionable course. The instructor is great at explaining how to apply the concepts to real life.",
      },
    ],
  },
  {
    id: 12,
    title: "Productivity and Time Management for the Overwhelmed",
    instructor: "Josh Paulsen",
    rating: 4.6,
    reviewCount: 94371,
    price: 469.0,
    originalPrice: 3219.0,
    currency: "INR",
    description:
      "Designed for those who feel constantly stressed and overwhelmed, this course teaches simple, effective strategies to manage your workload, regain control, and find a better work-life balance.",
    imageUrl: "/assets/PersonalDevelopmentPage/productivity.png",
    status: "trending",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "5h 00m",
    lectures: 45,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Identify the root causes of feeling overwhelmed",
      "Learn to say 'no' and set boundaries",
      "Create a minimalist and effective to-do list",
      "Implement a system for stress-free productivity",
      "Find sustainable ways to avoid burnout",
    ],
    requirements: ["An open mind and a desire for less stress"],
    whatYouWillLearn: [
      "Reduce stress and anxiety related to work",
      "Increase focus and efficiency",
      "Achieve a healthy work-life balance",
      "Develop habits that support long-term well-being",
    ],
    targetAudience: [
      "Anyone feeling overwhelmed and stressed",
      "Professionals struggling with burnout",
      "Parents trying to balance work and family life",
      "Students managing a heavy academic workload",
    ],
    subPage: "productivity",
    reviews: [
      {
        id: 1,
        user: "Kavita S.",
        date: "June 29, 2025",
        comment:
          "This course was a lifesaver. The advice on setting boundaries was exactly what I needed to hear.",
      },
      {
        id: 2,
        user: "Nikhil B.",
        date: "June 23, 2025",
        comment:
          "The strategies are simple and very effective. I'm no longer constantly stressed about my to-do list.",
      },
      {
        id: 3,
        user: "Sneha G.",
        date: "June 19, 2025",
        comment:
          "A must-do for anyone feeling overwhelmed. The course content is both practical and empathetic.",
      },
    ],
  },
];
export const featuredPersonalDevelopmentCourse = {
  title: "Storytelling Mastery: How to Tell Better Stories",
  instructor: "Video School, Phil Ebiner, and Ravinder Deol",
  rating: 4.8,
  reviewCount: 15,
  price: 449.0,
  originalPrice: 1679.0,
  currency: "INR",
  description:
    "Learn the secrets of powerful storytelling to engage your audience, whether you're a writer, a public speaker, or a business professional. This course covers the fundamental elements of a compelling narrative.",
  imageUrl: "/assets/PersonalDevelopmentPage/storytelling.png",
  status: "new",
  badge: "New",
  level: "All Levels",
  language: "English",
  duration: "2h 30m",
  lectures: 34,
  lastUpdated: "June 2025",
  subtitleLanguages: ["English"],
  highlights: [
    "Understand the core components of a story (hero's journey, etc.)",
    "Learn to structure a narrative for maximum impact",
    "Use emotional hooks to captivate your audience",
    "Apply storytelling to business presentations and pitches",
    "Practice exercises to hone your storytelling skills",
  ],
  requirements: ["A desire to communicate more effectively"],
  whatYouWillLearn: [
    "Tell stories that resonate with your audience",
    "Improve your public speaking and writing skills",
    "Make your messages more memorable and persuasive",
    "Connect with people on a deeper, emotional level",
  ],
  targetAudience: [
    "Writers and content creators",
    "Public speakers and presenters",
    "Marketers and sales professionals",
    "Anyone who wants to improve their communication skills",
  ],
  subPage: "communication",
  reviews: [
    {
      id: 1,
      user: "Ajay S.",
      date: "June 28, 2025",
      comment:
        "This course is fantastic! The concepts are easy to understand, and I'm already using them to make my presentations more engaging.",
    },
    {
      id: 2,
      user: "Smita D.",
      date: "June 24, 2025",
      comment:
        "The section on the hero's journey was a revelation. It's a powerful framework for so many types of stories.",
    },
    {
      id: 3,
      user: "Rahul K.",
      date: "June 20, 2025",
      comment:
        "Highly recommend for anyone who wants to improve their communication. The exercises were a great way to put theory into practice.",
    },
  ],
};
export const personalDevelopmentInstructors = [
  {
    name: "Akarsh Tyagi",
    expertise: "Speed Reading, Memory, Cognitive Science",
    rating: 4.8,
    students: "850,000",
    courses: 10,
    thumbnail: "https://placehold.co/100x100/36b85c/fff?text=AT",
  },
  {
    name: "Kartikay Kandpal",
    expertise: "Life Coaching, Psychology",
    rating: 4.7,
    students: "650,000",
    courses: 15,
    thumbnail: "https://placehold.co/100x100/1e90ff/fff?text=KK",
  },
  {
    name: "Avishkar",
    expertise: "Neuro-Linguistic Programming (NLP)",
    rating: 4.6,
    students: "420,000",
    courses: 8,
    thumbnail: "https://placehold.co/100x100/ff4500/fff?text=AV",
  },
  {
    name: "Chris Haroun",
    expertise: "Career Development, Job Searching",
    rating: 4.4,
    students: "1,500,000",
    courses: 20,
    thumbnail: "https://placehold.co/100x100/8a2be2/fff?text=CH",
  },
  {
    name: "Alexis Haselberger",
    expertise: "Productivity, Time Management",
    rating: 4.5,
    students: "900,000",
    courses: 12,
    thumbnail: "https://placehold.co/100x100/ffd700/fff?text=AH",
  },
  {
    name: "Romi Ochwani",
    expertise: "Meditation, Mindfulness, Wellness",
    rating: 5.0,
    students: "50,000",
    courses: 5,
    thumbnail: "https://placehold.co/100x100/008080/fff?text=RO",
  },
  {
    name: "Steve Ballinger",
    expertise: "AI Tools, Productivity",
    rating: 4.4,
    students: "2,100,000",
    courses: 7,
    thumbnail: "https://placehold.co/100x100/d3d3d3/fff?text=SB",
  },
];
export const personalDevelopmentTopics = [
  "Mindfulness",
  "Meditation",
  "Productivity",
  "Leadership",
  "Public Speaking",
  "Communication Skills",
  "Career Development",
  "Life Coaching",
  "Neuro-Linguistic Programming (NLP)",
  "Emotional Intelligence",
  "Habit Formation",
  "Stress Management",
  "Memory & Speed Reading",
  "Storytelling",
];
