export const dummyCourses = [
    {
      id: 1,
      tag: "Most Popular",
      title: "Become a SuperLearner® 2: Learn Speed Reading & Boost Memory",
      instructor: "Akarsh Tyagi, Lev Goldentouch, Anna Goldentouch",
      thumbnail: "https://via.placeholder.com/240x135?text=Course+1",
      rating: 4.3,
      reviews: 40520,
      price: 659,
      originalPrice: 4559,
      badges: ["Premium", "Bestseller"],
    },
    {
      id: 2,
      tag: "Most Popular",
      title: "Certified Life Coach Training (Beginner to Advanced)",
      instructor: "Kartikay Kandpal, The Academy of Applied Psychology",
      thumbnail: "https://via.placeholder.com/240x135?text=Course+2",
      rating: 4.6,
      reviews: 38285,
      price: 659,
      originalPrice: 4389,
      badges: ["Premium"],
    },
    {
      id: 3,
      tag: "Most Popular",
      title: "NLP Practitioner Course (Neuro-Linguistic Programming)",
      instructor: "Avishkar, The Academy of Applied Psychology",
      thumbnail: "https://via.placeholder.com/240x135?text=Course+3",
      rating: 4.6,
      reviews: 26388,
      price: 559,
      originalPrice: 3849,
      badges: ["Premium", "Bestseller"],
    },
    {
      id: 4,
      tag: "Most Popular",
      title: "The Complete Resume, LinkedIn & Get Your Dream Job Course!",
      instructor: "Chris Haroun",
      thumbnail: "https://via.placeholder.com/240x135?text=Course+4",
      rating: 4.4,
      reviews: 7234,
      price: 529,
      originalPrice: 3659,
      badges: ["Premium", "Bestseller"],
    },
  
    // 🆕 New Courses Section
    {
      id: 5,
      tag: "New",
      title: "Speak-up: Confident workplace presentations for beginners",
      instructor: "Mick Mason",
      thumbnail: "https://via.placeholder.com/240x135?text=New+Course+1",
      rating: 4.9,
      reviews: 5,
      price: 449,
      originalPrice: 1679,
      badges: ["New"],
    },
    {
      id: 6,
      tag: "New",
      title: "Business and Life Skills – All you need to succeed!",
      instructor: "Freedom Learning",
      thumbnail: "https://via.placeholder.com/240x135?text=New+Course+2",
      rating: 5.0,
      reviews: 45,
      price: 449,
      originalPrice: 1679,
      badges: ["New"],
    },
    {
      id: 7,
      tag: "New",
      title: "Naturopathy Fundamentals Course with Certification",
      instructor: "Ali Haider",
      thumbnail: "https://via.placeholder.com/240x135?text=New+Course+3",
      rating: 5.0,
      reviews: 6,
      price: 449,
      originalPrice: 1679,
      badges: ["New"],
    },
    {
      id: 8,
      tag: "New",
      title: "Meditate on Self: Heal, Empower & Awaken Within",
      instructor: "Romi Ochwani",
      thumbnail: "https://via.placeholder.com/240x135?text=New+Course+4",
      rating: 5.0,
      reviews: 6,
      price: 449,
      originalPrice: 1679,
      badges: ["New"],
    },
    {
        id: 9,
        tag: "Trending",
        title: "ChatGPT: Complete ChatGPT Course For Work 2025 (Ethically)!",
        instructor: "Steve Ballinger, MBA",
        thumbnail: "https://via.placeholder.com/240x135?text=Trending+Course+1",
        rating: 4.4,
        reviews: 114912,
        price: 659,
        originalPrice: 4129,
        badges: ["Premium", "Bestseller"],
      },
      {
        id: 10,
        tag: "Trending",
        title: "Applying Mindfulness to Develop Resilience and Wellbeing",
        instructor: "Robin Hills",
        thumbnail: "https://via.placeholder.com/240x135?text=Trending+Course+2",
        rating: 4.5,
        reviews: 5232,
        price: 449,
        originalPrice: 3199,
        badges: ["Premium"],
      },
      {
        id: 11,
        tag: "Trending",
        title: "Time Management Mastery: Do More, Stress Less",
        instructor: "Alexis Haselberger",
        thumbnail: "https://via.placeholder.com/240x135?text=Trending+Course+3",
        rating: 4.5,
        reviews: 82302,
        price: 469,
        originalPrice: 3779,
        badges: ["Premium"],
      },
      {
        id: 12,
        tag: "Trending",
        title: "Productivity and Time Management for the Overwhelmed",
        instructor: "Josh Paulsen",
        thumbnail: "https://via.placeholder.com/240x135?text=Trending+Course+4",
        rating: 4.6,
        reviews: 94371,
        price: 469,
        originalPrice: 3219,
        badges: ["Premium", "Bestseller"],
      }
      
  ];
  
  export const featuredCourse = {
    title: "Storytelling Mastery: How to Tell Better Stories",
    instructor: "Video School, Phil Ebiner, and Ravinder Deol",
    thumbnail: "https://via.placeholder.com/300x170?text=Storytelling+Course",
    rating: 4.8,
    reviews: 15,
    price: 449,
    originalPrice: 1679,
    badges: ["Premium", "Hot & New"],
    duration: "2.5 total hours",
    lectures: 34,
    updated: "June 2025",
  };
    