export const photographyCourses = [
  {
    id: 1,
    title: "Photography Masterclass: Complete Guide to Photography",
    instructor: "Emma Carter",
    rating: 4.8,
    reviewCount: 12345,
    price: 2999,
    originalPrice: 4999,
    currency: "INR",
    description:
      "Learn everything from camera settings to composition and storytelling. Perfect for beginners and enthusiasts.",
    imageUrl: "/assets/PhotographyVideoPage/Photography-Masterclass.png",
    status: "new",
    badge: "Bestseller",
    level: "Beginner",
    language: "English",
    duration: "14h 20m",
    lectures: 120,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Master your DSLR or Mirrorless camera",
      "Understand exposure triangle: ISO, Shutter, Aperture",
      "Learn composition techniques",
      "Practical exercises with real scenarios",
    ],
    requirements: [
      "Any camera (DSLR/Mirrorless/Phone)",
      "Willingness to practice",
    ],
    whatYouWillLearn: [
      "Take sharp and professional photos",
      "Use manual mode confidently",
      "Apply storytelling in photography",
    ],
    targetAudience: [
      "Beginners wanting to learn photography",
      "Hobbyists wanting to go pro",
      "Content creators",
    ],
    subPage: "Photography-Basics",
    reviews: [
      {
        id: 1,
        user: "Ravi K.",
        date: "July 10, 2025",
        comment:
          "Excellent breakdown of fundamentals. Helped me move from Auto mode to Manual mode!",
      },
    ],
  },
  {
    id: 2,
    title: "Creative Portrait Photography: Lighting & Composition",
    instructor: "Daniel Hughes",
    rating: 4.6,
    reviewCount: 8754,
    price: 2499,
    originalPrice: 3999,
    currency: "INR",
    description:
      "Learn how to capture stunning portraits with creative lighting setups and posing techniques.",
    imageUrl: "/assets/PhotographyVideoPage/Creative-Portrait-Photography.png",
    status: "popular",
    badge: "Highest Rated",
    level: "Intermediate",
    language: "English",
    duration: "9h 40m",
    lectures: 65,
    lastUpdated: "May 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Studio & natural light portrait setups",
      "Posing techniques for models",
      "Retouching basics in Lightroom & Photoshop",
    ],
    requirements: ["Basic knowledge of camera handling"],
    whatYouWillLearn: [
      "Shoot professional-quality portraits",
      "Master different light setups",
    ],
    targetAudience: ["Portrait photographers", "Freelancers", "YouTubers"],
    subPage: "Lighting-Techniques",
    reviews: [
      {
        id: 1,
        user: "Sophia D.",
        date: "June 5, 2025",
        comment:
          "Loved the lighting breakdowns. Great for intermediate learners.",
      },
    ],
  },
  {
    id: 3,
    title: "Video Editing with Adobe Premiere Pro 2025",
    instructor: "Michael Lee",
    rating: 4.7,
    reviewCount: 10230,
    price: 3199,
    originalPrice: 4599,
    currency: "INR",
    description:
      "Learn video editing from scratch using Adobe Premiere Pro. Includes transitions, color grading, and exporting.",
    imageUrl: "/assets/PhotographyVideoPage/Video-Editing-with-Adobe.png",
    status: "new",
    badge: "Bestseller",
    level: "Beginner to Advanced",
    language: "English",
    duration: "18h 15m",
    lectures: 95,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Editing basics to advanced techniques",
      "Professional transitions & effects",
      "Color grading and cinematic look",
    ],
    requirements: ["Adobe Premiere Pro installed"],
    whatYouWillLearn: ["Edit professional videos", "Color grade like a pro"],
    targetAudience: ["YouTubers", "Content creators", "Aspiring editors"],
    subPage: "Video-Editing",
    reviews: [
      {
        id: 1,
        user: "Arjun M.",
        date: "July 18, 2025",
        comment: "Great course. Learned color grading for my YouTube channel.",
      },
    ],
  },
  {
    id: 4,
    title: "Drone Photography & Cinematography",
    instructor: "Olivia White",
    rating: 4.5,
    reviewCount: 6543,
    price: 2799,
    originalPrice: 4299,
    currency: "INR",
    description:
      "Master drone flying, aerial shots, and cinematic movements for breathtaking visuals.",
    imageUrl:
      "/assets/PhotographyVideoPage/Drone-Photography-Cinematography.png",
    status: "popular",
    badge: "Trending",
    level: "Intermediate",
    language: "English",
    duration: "8h 50m",
    lectures: 70,
    lastUpdated: "April 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Drone regulations & safety",
      "Aerial photography techniques",
      "Drone cinematic movements",
    ],
    requirements: ["A drone with camera", "Basic photography knowledge"],
    whatYouWillLearn: ["Capture cinematic drone shots", "Edit drone footage"],
    targetAudience: ["Travel vloggers", "Filmmakers", "Event photographers"],
    subPage: "Drone-Photography",
    reviews: [
      {
        id: 1,
        user: "Vikram S.",
        date: "May 30, 2025",
        comment: "Helped me take my travel vlogs to the next level!",
      },
    ],
  },
  {
    id: 5,
    title: "Lightroom & Photoshop Photo Editing Masterclass",
    instructor: "Sophia Johnson",
    rating: 4.9,
    reviewCount: 14321,
    price: 3499,
    originalPrice: 4999,
    currency: "INR",
    description:
      "Edit photos like a pro using Lightroom and Photoshop. Covers RAW processing, retouching, and creative edits.",
    imageUrl: "/assets/PhotographyVideoPage/Lightroom-Photoshop-Photo.png",
    status: "new",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "15h 00m",
    lectures: 105,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Complete workflow for photo editing",
      "Retouch portraits & landscapes",
      "Advanced color grading techniques",
    ],
    requirements: ["Adobe Lightroom & Photoshop installed"],
    whatYouWillLearn: ["Create stunning edits", "Build photo editing workflow"],
    targetAudience: ["Photographers", "Designers", "Freelancers"],
    subPage: "Photo-Editing",
    reviews: [
      {
        id: 1,
        user: "Neha P.",
        date: "July 14, 2025",
        comment:
          "Amazing editing tips! My Instagram photos improved drastically.",
      },
    ],
  },
  {
    id: 6,
    title: "Street Photography: Capturing Authentic Moments",
    instructor: "Mark Evans",
    rating: 4.7,
    reviewCount: 7890,
    price: 2199,
    originalPrice: 3299,
    currency: "INR",
    description:
      "Learn to capture the soul of a city and its people. This course covers techniques for candid street photography, from composition to post-processing.",
    imageUrl: "/assets/PhotographyVideoPage/Street-Photography.png",
    status: "popular",
    badge: "Trending",
    level: "Intermediate",
    language: "English",
    duration: "7h 30m",
    lectures: 55,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Master candid shooting techniques",
      "Learn to use natural light on the street",
      "Develop your photographic eye",
      "Edit street photos for maximum impact",
    ],
    requirements: ["Any camera and lens"],
    whatYouWillLearn: [
      "Take compelling street photos",
      "Feel comfortable shooting in public",
      "Tell stories with your images",
    ],
    targetAudience: [
      "Aspiring street photographers",
      "Travelers",
      "Documentary photographers",
    ],
    subPage: "Photography-Basics",
    reviews: [
      {
        id: 1,
        user: "John D.",
        date: "July 20, 2025",
        comment:
          "This course gave me the confidence to go out and shoot. The tips on finding great light were invaluable.",
      },
    ],
  },
  {
    id: 7,
    title: "Food Photography: From Snap to Studio",
    instructor: "Isabelle Dupont",
    rating: 4.9,
    reviewCount: 9120,
    price: 2699,
    originalPrice: 3899,
    currency: "INR",
    description:
      "Create mouth-watering food photos for blogs, social media, and menus. Covers styling, lighting, and editing.",
    imageUrl: "/assets/PhotographyVideoPage/Food-Photography.png",
    status: "new",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "6h 15m",
    lectures: 45,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "French"],
    highlights: [
      "Master food styling and composition",
      "Use both natural and artificial light",
      "Post-processing for vibrant colors",
      "Build a portfolio of food photos",
    ],
    requirements: ["Any camera, a light source (natural or flash)"],
    whatYouWillLearn: [
      "Shoot stunning food photos",
      "Build a professional portfolio",
      "Work with different props and backdrops",
    ],
    targetAudience: [
      "Food bloggers",
      "Restaurateurs",
      "Chefs",
      "Instagrammers",
    ],
    subPage: "Photography-Basics",
    reviews: [
      {
        id: 1,
        user: "Priya L.",
        date: "August 15, 2025",
        comment:
          "I can't believe how much my photos improved! The styling tips were a total game-changer.",
      },
    ],
  },
  {
    id: 8,
    title: "Landscape & Travel Photography Guide",
    instructor: "Ben Harrison",
    rating: 4.7,
    reviewCount: 11500,
    price: 2899,
    originalPrice: 4199,
    currency: "INR",
    description:
      "Capture the beauty of nature and distant lands. Covers everything from sunrise shoots to astrophotography.",
    imageUrl: "/assets/PhotographyVideoPage/Landscape-Travel.png",
    status: "popular",
    badge: "Bestseller",
    level: "Beginner to Advanced",
    language: "English",
    duration: "11h 00m",
    lectures: 80,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Plan and execute successful landscape shoots",
      "Use filters and long exposures",
      "Advanced composition for travel photos",
      "Astrophotography essentials",
    ],
    requirements: ["A camera and tripod"],
    whatYouWillLearn: [
      "Take breathtaking landscape photos",
      "Capture the night sky",
      "Edit travel photos to pop",
    ],
    targetAudience: [
      "Travel photographers",
      "Hikers & nature lovers",
      "Bloggers",
    ],
    subPage: "Lighting-Techniques",
    reviews: [
      {
        id: 1,
        user: "Liam J.",
        date: "July 22, 2025",
        comment:
          "The instructor's passion for landscape photography is contagious. I learned so much about planning my shots.",
      },
    ],
  },
  {
    id: 9,
    title: "Wedding & Event Photography Business",
    instructor: "Laura Carter",
    rating: 4.5,
    reviewCount: 5678,
    price: 3599,
    originalPrice: 5199,
    currency: "INR",
    description:
      "Start your own photography business! Covers marketing, client communication, and shooting real weddings.",
    imageUrl: "/assets/PhotographyVideoPage/Wedding-Event-Photography.png",
    status: "new",
    badge: "Premium",
    level: "Advanced",
    language: "English",
    duration: "10h 30m",
    lectures: 75,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Build a professional portfolio",
      "Handle client inquiries and contracts",
      "Shoot ceremonies and receptions",
      "Post-processing a full wedding album",
    ],
    requirements: [
      "Intermediate photography skills",
      "Professional camera gear",
    ],
    whatYouWillLearn: [
      "Start a profitable photography business",
      "Master wedding day timelines",
      "Deliver a high-quality final product",
    ],
    targetAudience: [
      "Aspiring wedding photographers",
      "Event planners",
      "Freelancers",
    ],
    subPage: "Drone-Photography",
    reviews: [
      {
        id: 1,
        user: "Maria B.",
        date: "August 10, 2025",
        comment:
          "The business side of this course was invaluable. I now have a clear roadmap for my business.",
      },
    ],
  },
  {
    id: 10,
    title: "Mobile Photography: Shoot Like a Pro with Your Phone",
    instructor: "Chloe Smith",
    rating: 4.8,
    reviewCount: 15432,
    price: 1899,
    originalPrice: 2499,
    currency: "INR",
    description:
      "Your best camera is the one you have with you. Learn advanced techniques and apps to take stunning photos with just your smartphone.",
    imageUrl: "/assets/PhotographyVideoPage/Mobile-Photography.png",
    status: "new",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "5h 00m",
    lectures: 40,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Master smartphone camera settings",
      "Learn creative mobile editing apps",
      "Compose compelling shots on the go",
      "Share your photos on social media",
    ],
    requirements: ["A smartphone"],
    whatYouWillLearn: [
      "Take professional photos with your phone",
      "Edit photos directly on your mobile device",
      "Find your unique photographic style",
    ],
    targetAudience: ["Social media users", "Bloggers", "Casual photographers"],
    subPage: "Video-Editing",
    reviews: [
      {
        id: 1,
        user: "Sam C.",
        date: "July 25, 2025",
        comment:
          "I was shocked by how much I could do with my phone camera after this course. So many useful tips!",
      },
    ],
  },
  {
    id: 11,
    title: "Black & White Photography Essentials",
    instructor: "Ryan Miller",
    rating: 4.6,
    reviewCount: 4567,
    price: 1999,
    originalPrice: 2899,
    currency: "INR",
    description:
      "Explore the timeless art of black and white photography. Learn to see in monochrome and use light and shadow to create powerful images.",
    imageUrl: "/assets/PhotographyVideoPage/Black-White-Photography.png",
    status: "trending",
    badge: "Trending",
    level: "Beginner to Intermediate",
    language: "English",
    duration: "4h 45m",
    lectures: 35,
    lastUpdated: "June 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Understand tonal contrast and texture",
      "Master composition for monochrome",
      "Post-process B&W images in Lightroom",
      "Find inspiration from master photographers",
    ],
    requirements: ["Any camera that can shoot in RAW"],
    whatYouWillLearn: [
      "Create dramatic black and white photos",
      "Use light and shadow effectively",
      "Develop a unique artistic style",
    ],
    targetAudience: [
      "Artistic photographers",
      "Portrait photographers",
      "Street photographers",
    ],
    subPage: "Lighting-Techniques",
    reviews: [
      {
        id: 1,
        user: "Elena P.",
        date: "June 20, 2025",
        comment:
          "This course opened my eyes to the art of B&W. The lessons on light were particularly helpful.",
      },
    ],
  },
  {
    id: 12,
    title: "Nature & Wildlife Photography",
    instructor: "Greg Thompson",
    rating: 4.7,
    reviewCount: 9876,
    price: 2699,
    originalPrice: 3999,
    currency: "INR",
    description:
      "Learn the patience and techniques required to capture stunning photos of wildlife and the natural world.",
    imageUrl: "/assets/PhotographyVideoPage/Nature-Wildlife-Photography.png",
    status: "popular",
    badge: "Premium",
    level: "Intermediate",
    language: "English",
    duration: "9h 20m",
    lectures: 70,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "German"],
    highlights: [
      "Understand wildlife behavior",
      "Master telephoto lens techniques",
      "Learn to use blind and camouflage",
      "Ethical wildlife photography practices",
    ],
    requirements: ["A camera with a telephoto lens"],
    whatYouWillLearn: [
      "Capture incredible photos of animals",
      "Be prepared for any weather condition",
      "Tell a story through your nature photography",
    ],
    targetAudience: ["Wildlife enthusiasts", "Nature lovers", "Travelers"],
    subPage: "Drone-Photography",
    reviews: [
      {
        id: 1,
        user: "Ankit S.",
        date: "July 25, 2025",
        comment:
          "The tips on getting close to wildlife without disturbing them were golden. I can't wait to try these techniques.",
      },
    ],
  },
  {
    id: 13,
    title: "Product Photography for E-commerce",
    instructor: "Claire Davis",
    rating: 4.8,
    reviewCount: 8123,
    price: 2399,
    originalPrice: 3599,
    currency: "INR",
    description:
      "Create professional product photos that sell. Learn to set up a home studio, manage lighting, and edit images for your online store.",
    imageUrl:
      "/assets/PhotographyVideoPage/Product-Photography-for-E-commerce.png",
    status: "new",
    badge: "Bestseller",
    level: "Beginner",
    language: "English",
    duration: "6h 50m",
    lectures: 50,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Set up a DIY product photography studio",
      "Master light placement for products",
      "Post-process images for a clean look",
      "Create high-quality images for your online store",
    ],
    requirements: ["Any camera (even a phone)", "A light source"],
    whatYouWillLearn: [
      "Shoot professional photos of your products",
      "Increase sales with better visuals",
      "Save money on professional photographers",
    ],
    targetAudience: [
      "E-commerce sellers",
      "Small business owners",
      "Product marketers",
    ],
    subPage: "Photo-Editing",
    reviews: [
      {
        id: 1,
        user: "Rajesh T.",
        date: "August 12, 2025",
        comment:
          "This course paid for itself on the first day. My product photos look so much better now.",
      },
    ],
  },
  {
    id: 14,
    title: "Cinematography for Beginners",
    instructor: "Adam Foster",
    rating: 4.7,
    reviewCount: 7543,
    price: 2999,
    originalPrice: 4499,
    currency: "INR",
    description:
      "Go beyond basic video and learn the art of cinematography. Understand camera movement, shot composition, and visual storytelling.",
    imageUrl: "/assets/PhotographyVideoPage/Cinematography-for-Beginners.png",
    status: "popular",
    badge: "Premium",
    level: "Beginner to Intermediate",
    language: "English",
    duration: "10h 15m",
    lectures: 75,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Master the basics of cinematography",
      "Learn camera movements and blocking",
      "Understand lighting for video",
      "Create professional-looking videos",
    ],
    requirements: ["A camera that can shoot video"],
    whatYouWillLearn: [
      "Shoot cinematic videos and films",
      "Develop a strong visual style",
      "Tell a compelling story with video",
    ],
    targetAudience: ["Aspiring filmmakers", "YouTubers", "Content creators"],
    subPage: "Video-Editing",
    reviews: [
      {
        id: 1,
        user: "Kiran R.",
        date: "July 28, 2025",
        comment:
          "This course taught me the theory behind great visuals. My videos now look so much more professional.",
      },
    ],
  },
  {
    id: 15,
    title: "Wildlife Photography: In the Field",
    instructor: "Emily Stone",
    rating: 4.8,
    reviewCount: 9210,
    price: 3199,
    originalPrice: 4799,
    currency: "INR",
    description:
      "Get out of the classroom and into the field. This hands-on course teaches practical skills for shooting wildlife in their natural habitat.",
    imageUrl: "/assets/PhotographyVideoPage/Wildlife-Photography.png",
    status: "trending",
    badge: "Bestseller",
    level: "Intermediate",
    language: "English",
    duration: "12h 00m",
    lectures: 90,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English"],
    highlights: [
      "Patience and observation techniques",
      "Shooting in challenging conditions",
      "Capturing moments in motion",
      "Essential gear for wildlife shoots",
    ],
    requirements: ["A camera and telephoto lens"],
    whatYouWillLearn: [
      "Take professional wildlife photos",
      "Improve your fieldcraft skills",
      "Capture compelling animal portraits",
    ],
    targetAudience: [
      "Wildlife photographers",
      "Outdoor enthusiasts",
      "Nature lovers",
    ],
    subPage: "Photo-Editing",
    reviews: [
      {
        id: 1,
        user: "David B.",
        date: "August 20, 2025",
        comment:
          "The tips on shooting in low light and bad weather were fantastic. I feel much more prepared for my next trip.",
      },
    ],
  },
];

export const photographyInstructors = [
  {
    name: "Michael Lee",
    expertise: "Video Editing, Cinematography",
    rating: 4.7,
    students: "850,000",
    courses: 25,
    thumbnail: "https://placehold.co/100x100/e74c3c/fff?text=ML",
  },
  {
    name: "Emma Carter",
    expertise: "Photography Basics, Composition",
    rating: 4.8,
    students: "1,500,000",
    courses: 20,
    thumbnail: "https://placehold.co/100x100/3498db/fff?text=EC",
  },
  {
    name: "Sophia Johnson",
    expertise: "Photo Editing, Lightroom & Photoshop",
    rating: 4.9,
    students: "900,000",
    courses: 15,
    thumbnail: "https://placehold.co/100x100/f1c40f/fff?text=SJ",
  },
  {
    name: "Olivia White",
    expertise: "Drone Photography, Cinematography",
    rating: 4.5,
    students: "600,000",
    courses: 10,
    thumbnail: "https://placehold.co/100x100/2ecc71/fff?text=OW",
  },
  {
    name: "Mark Evans",
    expertise: "Street Photography, Storytelling",
    rating: 4.7,
    students: "450,000",
    courses: 8,
    thumbnail: "https://placehold.co/100x100/95a5a6/fff?text=ME",
  },
];

export const PhotographyTopics = [
  "Camera Basics",
  "Photo Editing",
  "Video Editing",
  "Drone Photography",
  "Portraiture",
  "Street Photography",
  "Wildlife Photography",
  "Lighting Techniques",
  "Adobe Photoshop",
  "Adobe Lightroom",
  "Final Cut Pro",
  "Storytelling in Film",
  "Color Grading",
  "Cinematography",
  "Mobile Videography",
];
