export const leadershipCourses = [
  {
    id: 1,
    title: "Leadership: Practical Leadership Skills",
    instructor: "Chris Croft",
    rating: 4.6,
    reviewCount: 68230,
    price: 649,
    originalPrice: 3999,
    currency: "INR",
    description:
      "Learn essential, practical skills to lead your team effectively, including motivation, delegation, and communication.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/leadership1.png",
    status: "trending",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "6h 15m",
    lectures: 75,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Improve your communication and delegation",
      "Boost team morale and productivity",
      "Handle conflicts with confidence",
      "Develop a strong leadership mindset",
    ],
    requirements: [
      "No prior leadership experience needed",
      "Desire to improve your leadership skills",
    ],
    whatYouWillLearn: [
      "Lead and inspire your team effectively",
      "Build trust and respect with your colleagues",
      "Give constructive feedback",
      "Motivate others to achieve goals",
    ],
    targetAudience: [
      "New and aspiring managers",
      "Team leaders",
      "Anyone who wants to improve their influence",
    ],
    subPage: "leadership",
    reviews: [
      {
        id: 1,
        user: "Priya S.",
        date: "July 20, 2025",
        comment:
          "Chris Croft makes leadership easy to understand. The tips are actionable and I've already seen a difference!",
      },
    ],
  },
  {
    id: 2,
    title: "Modern Leadership: How to Lead in the 21st Century",
    instructor: "Deborah Grayson Riegel",
    rating: 4.8,
    reviewCount: 320,
    price: 599,
    originalPrice: 3599,
    currency: "INR",
    description:
      "Discover the new rules of modern leadership, focusing on emotional intelligence, agility, and leading remote teams.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/leadership2.png",
    status: "new",
    badge: "New",
    level: "Intermediate",
    language: "English",
    duration: "5h 45m",
    lectures: 60,
    lastUpdated: "September 2025",
    subtitleLanguages: ["English", "German"],
    highlights: [
      "Lead with emotional intelligence",
      "Navigate change and uncertainty",
      "Master virtual team management",
      "Create a culture of psychological safety",
    ],
    requirements: [
      "Basic understanding of team dynamics",
      "Open mind to new leadership approaches",
    ],
    whatYouWillLearn: [
      "Adapt your leadership style to modern challenges",
      "Build resilient and high-performing teams",
      "Enhance your coaching and mentoring skills",
      "Foster innovation within your organization",
    ],
    targetAudience: [
      "Experienced managers transitioning to modern leadership",
      "Project managers",
      "Entrepreneurs and business owners",
    ],
    subPage: "leadership",
    reviews: [
      {
        id: 1,
        user: "Ankit V.",
        date: "September 8, 2025",
        comment:
          "Highly relevant for today's world. The section on leading remote teams was particularly valuable.",
      },
    ],
  },
  {
    id: 3,
    title: "Emotional Intelligence & Leadership",
    instructor: "Robin Hills",
    rating: 4.7,
    reviewCount: 12230,
    price: 599,
    originalPrice: 2999,
    currency: "INR",
    description:
      "Unlock the power of emotional intelligence to become a more empathetic, effective, and influential leader.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/leadership3.png",
    status: "most popular",
    badge: "Premium",
    level: "All Levels",
    language: "English",
    duration: "7h 30m",
    lectures: 95,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "French"],
    highlights: [
      "Understand and manage your emotions",
      "Recognize and influence the emotions of others",
      "Improve decision-making and problem-solving",
      "Build stronger relationships and trust",
    ],
    requirements: [
      "Willingness to self-reflect and learn",
      "Commitment to personal growth",
    ],
    whatYouWillLearn: [
      "Apply emotional intelligence in daily leadership situations",
      "Increase self-awareness and self-regulation",
      "Develop empathy and social skills",
      "Create a positive and supportive team environment",
    ],
    targetAudience: [
      "Leaders and managers at any level",
      "HR professionals and coaches",
      "Anyone looking to enhance their interpersonal skills",
    ],
    subPage: "leadership",
    reviews: [
      {
        id: 1,
        user: "Sneha G.",
        date: "August 12, 2025",
        comment:
          "A life-changing course! It’s not just about leadership, it's about becoming a better person.",
      },
    ],
  },
];

export const productivityCourses = [
  {
    id: 1,
    title: "Productivity Masterclass: Create a Custom System",
    instructor: "Ali Abdaal",
    rating: 4.8,
    reviewCount: 28500,
    price: 679,
    originalPrice: 3599,
    currency: "INR",
    description:
      "Learn how to build a personalized productivity system to manage your time, tasks, and projects efficiently.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/productivity1.png",
    status: "most popular",
    badge: "Bestseller",
    level: "Beginner",
    language: "English",
    duration: "8h 40m",
    lectures: 110,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Design a productivity system that works for you",
      "Master time-blocking and task management",
      "Overcome procrastination and boost focus",
      "Use tools like Notion and Todoist effectively",
    ],
    requirements: [
      "Desire to be more organized and productive",
      "Basic computer literacy",
    ],
    whatYouWillLearn: [
      "Create a custom workflow for your goals",
      "Prioritize tasks using proven methods",
      "Improve your focus and avoid distractions",
      "Achieve more in less time",
    ],
    targetAudience: [
      "Students and professionals",
      "Freelancers and entrepreneurs",
      "Anyone struggling with time management",
    ],
    subPage: "productivity",
    reviews: [
      {
        id: 1,
        user: "Rahul M.",
        date: "July 25, 2025",
        comment:
          "This course completely changed my approach to work. Ali's advice is practical and easy to follow.",
      },
    ],
  },
  {
    id: 2,
    title: "Getting Things Done with Notion & Productivity Hacks",
    instructor: "Thomas Frank",
    rating: 4.7,
    reviewCount: 9350,
    price: 569,
    originalPrice: 3199,
    currency: "INR",
    description:
      "Utilize the power of Notion and other productivity hacks to streamline your life and get more done effortlessly.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/productivity2.png",
    status: "trending",
    badge: "Premium",
    level: "Intermediate",
    language: "English",
    duration: "10h 10m",
    lectures: 90,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Build a complete system in Notion",
      "Implement the 'Getting Things Done' (GTD) framework",
      "Automate repetitive tasks",
      "Find and use the best productivity apps",
    ],
    requirements: [
      "Basic familiarity with Notion",
      "Access to a computer or device",
    ],
    whatYouWillLearn: [
      "Organize your life and work with a unified system",
      "Reduce mental clutter and stress",
      "Boost your efficiency and output",
      "Set and achieve your goals consistently",
    ],
    targetAudience: [
      "Notion users looking to go to the next level",
      "Professionals seeking advanced productivity techniques",
      "Anyone interested in modern productivity tools",
    ],
    subPage: "productivity",
    reviews: [
      {
        id: 1,
        user: "Aisha T.",
        date: "August 18, 2025",
        comment:
          "Thomas's insights into Notion are incredible. My workflow is so much cleaner now.",
      },
    ],
  },
  {
    id: 3,
    title: "Deep Work: Break Distractions & Focus Better",
    instructor: "Cal Newport (Unofficial)",
    rating: 4.9,
    reviewCount: 512,
    price: 499,
    originalPrice: 2999,
    currency: "INR",
    description:
      "Learn the art of 'deep work' to focus without distraction on a cognitively demanding task and produce high-quality work faster.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/productivity3.png",
    status: "new",
    badge: "New",
    level: "Beginner",
    language: "English",
    duration: "4h 50m",
    lectures: 55,
    lastUpdated: "September 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Understand the science of deep work",
      "Train your brain to focus for long periods",
      "Create distraction-free environments",
      "Develop rituals for peak performance",
    ],
    requirements: [
      "Willingness to change your work habits",
      "Desire to increase your output and quality",
    ],
    whatYouWillLearn: [
      "Perform difficult tasks efficiently",
      "Overcome digital distractions",
      "Become highly valuable in a competitive economy",
      "Structure your day for maximum focus",
    ],
    targetAudience: [
      "Knowledge workers and professionals",
      "Students",
      "Anyone who feels overwhelmed by constant distractions",
    ],
    subPage: "productivity",
    reviews: [
      {
        id: 1,
        user: "Kunal J.",
        date: "September 2, 2025",
        comment:
          "This course is a game-changer. I finally feel in control of my attention.",
      },
    ],
  },
];

export const careerDevelopmentCourses = [
  {
    id: 1,
    title: "Career Hacking™: Resume, LinkedIn, Interviewing + More",
    instructor: "Eazl",
    rating: 4.6,
    reviewCount: 52000,
    price: 659,
    originalPrice: 3899,
    currency: "INR",
    description:
      "Your all-in-one guide to landing your dream job, from crafting a killer resume to acing your interview and building a powerful LinkedIn profile.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/career1.png",
    status: "most popular",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "11h 50m",
    lectures: 140,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Create a professional, modern resume",
      "Optimize your LinkedIn for job opportunities",
      "Practice and master interview skills",
      "Negotiate your salary with confidence",
    ],
    requirements: [
      "No specific requirements",
      "Willingness to apply the strategies",
    ],
    whatYouWillLearn: [
      "Stand out in a crowded job market",
      "Effectively network and find hidden jobs",
      "Communicate your value to employers",
      "Build a long-term career strategy",
    ],
    targetAudience: [
      "Job seekers and recent graduates",
      "Professionals looking for a career change",
      "Anyone wanting to improve their career trajectory",
    ],
    subPage: "career-development",
    reviews: [
      {
        id: 1,
        user: "Divya R.",
        date: "August 1, 2025",
        comment:
          "This course is a complete roadmap for job hunting. The resume templates were especially helpful.",
      },
    ],
  },
  {
    id: 2,
    title: "Personal Branding for Career Growth",
    instructor: "Chelsea Krost",
    rating: 4.5,
    reviewCount: 10450,
    price: 549,
    originalPrice: 2899,
    currency: "INR",
    description:
      "Build a powerful personal brand that showcases your unique value and opens up new opportunities for career advancement.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/career2.png",
    status: "trending",
    badge: "Premium",
    level: "Beginner",
    language: "English",
    duration: "7h 20m",
    lectures: 85,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "Portuguese"],
    highlights: [
      "Define your unique personal brand",
      "Leverage social media for professional growth",
      "Network with influential people",
      "Become a recognized expert in your field",
    ],
    requirements: [
      "No specific requirements",
      "Desire to market yourself effectively",
    ],
    whatYouWillLearn: [
      "Stand out from the competition",
      "Attract opportunities instead of chasing them",
      "Build a strong professional reputation",
      "Increase your visibility and credibility",
    ],
    targetAudience: [
      "Entrepreneurs and freelancers",
      "Professionals looking to grow their influence",
      "Anyone who wants to control their professional narrative",
    ],
    subPage: "career-development",
    reviews: [
      {
        id: 1,
        user: "Vikram P.",
        date: "August 20, 2025",
        comment:
          "Chelsea provides a clear, step-by-step guide to personal branding. It's a must-take for anyone serious about their career.",
      },
    ],
  },
  {
    id: 3,
    title: "Job Interview Success: Ace Any Interview",
    instructor: "Lindsey Berger",
    rating: 4.9,
    reviewCount: 243,
    price: 479,
    originalPrice: 1999,
    currency: "INR",
    description:
      "Gain the confidence and skills to ace your next job interview, from behavioral questions to case studies and salary negotiation.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/career3.png",
    status: "new",
    badge: "New",
    level: "Beginner",
    language: "English",
    duration: "5h 15m",
    lectures: 65,
    lastUpdated: "September 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Prepare for common and difficult interview questions",
      "Learn effective communication techniques",
      "Master body language and non-verbal cues",
      "Follow up professionally and effectively",
    ],
    requirements: [
      "Willingness to practice mock interviews",
      "Desire to land a new job",
    ],
    whatYouWillLearn: [
      "Feel confident and prepared for any interview",
      "Tell compelling stories about your experience",
      "Handle tough questions with ease",
      "Make a lasting positive impression",
    ],
    targetAudience: [
      "Job seekers at any stage of their career",
      "Students preparing for their first interviews",
      "Anyone who wants to overcome interview anxiety",
    ],
    subPage: "career-development",
    reviews: [
      {
        id: 1,
        user: "Aditi S.",
        date: "September 5, 2025",
        comment:
          "This course is amazing! I feel so much more prepared for my interviews now. The tips are super helpful.",
      },
    ],
  },
];

export const emotionalIntelligenceCourses = [
  {
    id: 1,
    title: "Emotional Intelligence at Work: Learn from Psychology",
    instructor: "Robin Hills",
    rating: 4.7,
    reviewCount: 16800,
    price: 499,
    originalPrice: 3299,
    currency: "INR",
    description:
      "Apply psychological principles to develop your emotional intelligence and thrive in any professional environment.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/eq1.png",
    status: "trending",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "8h 5m",
    lectures: 98,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Understand the four components of EQ",
      "Manage stress and difficult emotions",
      "Improve your social and communication skills",
      "Influence and inspire your colleagues",
    ],
    requirements: [
      "Desire to improve your professional relationships",
      "Open mind to self-improvement",
    ],
    whatYouWillLearn: [
      "Navigate workplace dynamics with ease",
      "Build stronger, more trusting relationships",
      "Handle conflict constructively",
      "Boost your career by improving your EQ",
    ],
    targetAudience: [
      "Professionals at all levels",
      "Team leaders and managers",
      "Anyone looking to improve their soft skills",
    ],
    subPage: "emotional-intelligence",
    reviews: [
      {
        id: 1,
        user: "Gaurav L.",
        date: "July 28, 2025",
        comment:
          "A fantastic course on a critical topic. Robin's explanations are clear and backed by science.",
      },
    ],
  },
  {
    id: 2,
    title: "Mastering Self-Awareness and Social Skills",
    instructor: "Briana Johnson",
    rating: 4.6,
    reviewCount: 7850,
    price: 469,
    originalPrice: 2799,
    currency: "INR",
    description:
      "Develop the self-awareness to understand your own emotions and the social skills to connect deeply with others.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/eq2.png",
    status: "most popular",
    badge: "Premium",
    level: "Beginner",
    language: "English",
    duration: "6h 45m",
    lectures: 78,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "German"],
    highlights: [
      "Identify your core emotions and triggers",
      "Improve active listening and empathy",
      "Communicate more effectively and assertively",
      "Overcome shyness and social anxiety",
    ],
    requirements: [
      "Willingness to explore your own feelings",
      "Desire to build better relationships",
    ],
    whatYouWillLearn: [
      "Become more self-aware and confident",
      "Read social cues and understand others' perspectives",
      "Express yourself clearly and respectfully",
      "Create a strong network of connections",
    ],
    targetAudience: [
      "Anyone who wants to improve their social life",
      "Individuals struggling with self-awareness",
      "Professionals in client-facing roles",
    ],
    subPage: "emotional-intelligence",
    reviews: [
      {
        id: 1,
        user: "Rajesh K.",
        date: "August 15, 2025",
        comment:
          "This course provided practical exercises that truly helped me understand myself and others better.",
      },
    ],
  },
  {
    id: 3,
    title: "EQ for Leaders and Managers",
    instructor: "John Williams",
    rating: 4.8,
    reviewCount: 330,
    price: 489,
    originalPrice: 1999,
    currency: "INR",
    description:
      "A specialized course for leaders, focusing on how emotional intelligence drives team performance and organizational success.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/eq3.png",
    status: "new",
    badge: "New",
    level: "Intermediate",
    language: "English",
    duration: "4h 20m",
    lectures: 50,
    lastUpdated: "September 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Coach and mentor your team with empathy",
      "Motivate others through emotional connection",
      "Lead through difficult times with composure",
      "Build a positive and high-trust team culture",
    ],
    requirements: [
      "Existing leadership or management role",
      "Desire to lead with greater impact",
    ],
    whatYouWillLearn: [
      "Boost your team's productivity and morale",
      "Reduce workplace conflict and stress",
      "Make better, more balanced decisions",
      "Become a highly respected and effective leader",
    ],
    targetAudience: [
      "Team leaders and managers",
      "HR professionals",
      "Senior executives",
    ],
    subPage: "emotional-intelligence",
    reviews: [
      {
        id: 1,
        user: "Neha R.",
        date: "September 10, 2025",
        comment:
          "A compact yet powerful course. John's insights are incredibly useful for anyone in a leadership position.",
      },
    ],
  },
];

export const stressManagementCourses = [
  {
    id: 1,
    title: "Stress Management: 40+ Easy Ways to Deal with Stress",
    instructor: "Kain Ramsay",
    rating: 4.6,
    reviewCount: 18340,
    price: 499,
    originalPrice: 3099,
    currency: "INR",
    description:
      "A comprehensive course with over 40 practical techniques to manage and reduce stress in your daily life and work.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/stress1.png",
    status: "most popular",
    badge: "Bestseller",
    level: "All Levels",
    language: "English",
    duration: "6h 25m",
    lectures: 70,
    lastUpdated: "August 2025",
    subtitleLanguages: ["English", "Hindi"],
    highlights: [
      "Identify your personal stress triggers",
      "Learn effective breathing and relaxation techniques",
      "Develop a positive mindset",
      "Build resilience to cope with future stress",
    ],
    requirements: [
      "Willingness to practice new habits",
      "No prior experience needed",
    ],
    whatYouWillLearn: [
      "Reduce anxiety and daily stress",
      "Improve your sleep and energy levels",
      "Maintain calm in difficult situations",
      "Live a more balanced and peaceful life",
    ],
    targetAudience: [
      "Anyone experiencing high levels of stress",
      "Students and professionals",
      "Individuals seeking mental wellness techniques",
    ],
    subPage: "stress-management",
    reviews: [
      {
        id: 1,
        user: "Sanjay D.",
        date: "July 22, 2025",
        comment:
          "The variety of techniques is amazing. I found several that worked perfectly for me.",
      },
    ],
  },
  {
    id: 2,
    title: "Mindfulness and Stress Relief for Daily Life",
    instructor: "Greg de Vries",
    rating: 4.5,
    reviewCount: 10290,
    price: 459,
    originalPrice: 2599,
    currency: "INR",
    description:
      "Integrate simple mindfulness practices into your daily routine to reduce stress, increase focus, and find inner calm.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/stress2.png",
    status: "trending",
    badge: "Premium",
    level: "Beginner",
    language: "English",
    duration: "5h 10m",
    lectures: 60,
    lastUpdated: "July 2025",
    subtitleLanguages: ["English", "French"],
    highlights: [
      "Learn guided meditation and breathing exercises",
      "Practice mindful eating and walking",
      "Increase self-awareness and presence",
      "Cultivate a sense of calm and well-being",
    ],
    requirements: [
      "No prior meditation experience required",
      "A quiet space to practice",
    ],
    whatYouWillLearn: [
      "Effectively manage thoughts and emotions",
      "Break the cycle of stress and worry",
      "Improve your ability to focus and concentrate",
      "Respond to life's challenges with composure",
    ],
    targetAudience: [
      "Anyone new to mindfulness and meditation",
      "Individuals seeking to manage anxiety",
      "Busy professionals looking for a mental reset",
    ],
    subPage: "stress-management",
    reviews: [
      {
        id: 1,
        user: "Pooja V.",
        date: "August 10, 2025",
        comment:
          "This course is a gentle and effective introduction to mindfulness. It's now a part of my daily routine.",
      },
    ],
  },
  {
    id: 3,
    title: "Beat Burnout: Resilience & Recovery Techniques",
    instructor: "Lindsay Gordon",
    rating: 4.9,
    reviewCount: 142,
    price: 429,
    originalPrice: 1799,
    currency: "INR",
    description:
      "A specialized course to help you recognize, prevent, and recover from burnout with practical, science-backed strategies.",
    imageUrl: "/assets/PersonalDevelopmentPage/subPages/stress3.png",
    status: "new",
    badge: "New",
    level: "All Levels",
    language: "English",
    duration: "4h 30m",
    lectures: 55,
    lastUpdated: "September 2025",
    subtitleLanguages: ["English", "Spanish"],
    highlights: [
      "Identify the warning signs of burnout",
      "Create healthy work-life boundaries",
      "Develop habits for sustained energy",
      "Learn techniques for full recovery and rest",
    ],
    requirements: [
      "No specific requirements",
      "Desire to prevent or recover from burnout",
    ],
    whatYouWillLearn: [
      "Recognize the root causes of your stress",
      "Build mental and physical resilience",
      "Establish a routine that supports your well-being",
      "Work smarter, not harder, to avoid exhaustion",
    ],
    targetAudience: [
      "Professionals in high-stress jobs",
      "Students with heavy academic loads",
      "Anyone feeling overwhelmed and exhausted",
    ],
    subPage: "stress-management",
    reviews: [
      {
        id: 1,
        user: "Kartik R.",
        date: "September 9, 2025",
        comment:
          "This course was exactly what I needed. It's so relevant and provides a clear plan to beat burnout.",
      },
    ],
  },
];

export const personalDevelopmentTopics = [
  "Life Coach Training",
  "Personal Development",
  "Leadership",
  "Personal Transformation",
  "Personal Productivity",
  "ChatGPT",
  "Neuro-Linguistic Programming (NLP)",
  "Communication Skills",
  "Coaching",
  "Speed Reading",
];
export const personalDevelopmentInstructors = [
  {
    name: "Joeel & Natalie",
    expertise: "Life Coach Training, Personal Success",
    rating: 4.6,
    students: "7,78,240",
    courses: 126,
    thumbnail: "/assets/business/testimonial-person.png",
  },
  {
    name: "Steve Ballinger, MBA",
    expertise: "ChatGPT, AI Content Generation",
    rating: 4.5,
    students: "9,43,525",
    courses: 87,
    thumbnail: "/assets/business/testimonial-person.png",
  },
  {
    name: "Kain Ramsay",
    expertise: "Life Coach Training, NLP",
    rating: 4.6,
    students: "6,76,145",
    courses: 30,
    thumbnail: "/assets/business/testimonial-person.png",
  },
  {
    name: "TJ Walker",
    expertise: "Public Speaking, Soft Skills",
    rating: 4.5,
    students: "21,33,274",
    courses: 243,
    thumbnail: "/assets/business/testimonial-person.png",
  },
  {
    name: "Madhu Nair PMP®",
    expertise: "Project Management, Book Cover Design",
    rating: 4.6,
    students: "32,526",
    courses: 10,
    thumbnail: "/assets/business/testimonial-person.png",
  },
];
