export const leadershipCourses = [
  {
    id: 1,
    tag: "Trending",
    title: "Leadership: Practical Leadership Skills",
    instructor: "Chris Croft",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/leadership1.png",
    rating: 4.6,
    reviews: 68230,
    price: 649,
    originalPrice: 3999,
    badges: ["Premium", "Bestseller"],
  },
  {
    id: 2,
    tag: "New",
    title: "Modern Leadership: How to Lead in the 21st Century",
    instructor: "Deborah Grayson Riegel",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/leadership2.png",
    rating: 4.8,
    reviews: 320,
    price: 599,
    originalPrice: 3599,
    badges: ["New"],
  },
  {
    id: 3,
    tag: "Most Popular",
    title: "Emotional Intelligence & Leadership",
    instructor: "Robin Hills",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/leadership3.png",
    rating: 4.7,
    reviews: 12230,
    price: 599,
    originalPrice: 2999,
    badges: ["Premium"],
  },
];
export const productivityCourses = [
  {
    id: 1,
    tag: "Most Popular",
    title: "Productivity Masterclass: Create a Custom System",
    instructor: "Ali Abdaal",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/productivity1.png",
    rating: 4.8,
    reviews: 28500,
    price: 679,
    originalPrice: 3599,
    badges: ["Premium", "Bestseller"],
  },
  {
    id: 2,
    tag: "Trending",
    title: "Getting Things Done with Notion & Productivity Hacks",
    instructor: "Thomas Frank",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/productivity2.png",
    rating: 4.7,
    reviews: 9350,
    price: 569,
    originalPrice: 3199,
    badges: ["Premium"],
  },
  {
    id: 3,
    tag: "New",
    title: "Deep Work: Break Distractions & Focus Better",
    instructor: "Cal Newport (Unofficial)",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/productivity3.png",
    rating: 4.9,
    reviews: 512,
    price: 499,
    originalPrice: 2999,
    badges: ["New"],
  },
];
export const careerDevelopmentCourses = [
  {
    id: 1,
    tag: "Most Popular",
    title: "Career Hacking™: Resume, LinkedIn, Interviewing + More",
    instructor: "Eazl",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/career1.png",
    rating: 4.6,
    reviews: 52000,
    price: 659,
    originalPrice: 3899,
    badges: ["Premium", "Bestseller"],
  },
  {
    id: 2,
    tag: "Trending",
    title: "Personal Branding for Career Growth",
    instructor: "Chelsea Krost",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/career2.png",
    rating: 4.5,
    reviews: 10450,
    price: 549,
    originalPrice: 2899,
    badges: ["Premium"],
  },
  {
    id: 3,
    tag: "New",
    title: "Job Interview Success: Ace Any Interview",
    instructor: "Lindsey Berger",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/career3.png",
    rating: 4.9,
    reviews: 243,
    price: 479,
    originalPrice: 1999,
    badges: ["New"],
  },
];
export const emotionalIntelligenceCourses = [
  {
    id: 1,
    tag: "Trending",
    title: "Emotional Intelligence at Work: Learn from Psychology",
    instructor: "Robin Hills",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/eq1.png",
    rating: 4.7,
    reviews: 16800,
    price: 499,
    originalPrice: 3299,
    badges: ["Premium", "Bestseller"],
  },
  {
    id: 2,
    tag: "Most Popular",
    title: "Mastering Self-Awareness and Social Skills",
    instructor: "Briana Johnson",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/eq2.png",
    rating: 4.6,
    reviews: 7850,
    price: 469,
    originalPrice: 2799,
    badges: ["Premium"],
  },
  {
    id: 3,
    tag: "New",
    title: "EQ for Leaders and Managers",
    instructor: "John Williams",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/eq3.png",
    rating: 4.8,
    reviews: 330,
    price: 489,
    originalPrice: 1999,
    badges: ["New"],
  },
];
export const stressManagementCourses = [
  {
    id: 1,
    tag: "Most Popular",
    title: "Stress Management: 40+ Easy Ways to Deal with Stress",
    instructor: "Kain Ramsay",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/stress1.png",
    rating: 4.6,
    reviews: 18340,
    price: 499,
    originalPrice: 3099,
    badges: ["Premium", "Bestseller"],
  },
  {
    id: 2,
    tag: "Trending",
    title: "Mindfulness and Stress Relief for Daily Life",
    instructor: "Greg de Vries",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/stress2.png",
    rating: 4.5,
    reviews: 10290,
    price: 459,
    originalPrice: 2599,
    badges: ["Premium"],
  },
  {
    id: 3,
    tag: "New",
    title: "Beat Burnout: Resilience & Recovery Techniques",
    instructor: "Lindsay Gordon",
    thumbnail: "/assets/PersonalDevelopmentPage/subPages/stress3.png",
    rating: 4.9,
    reviews: 142,
    price: 429,
    originalPrice: 1799,
    badges: ["New"],
  },
];
